from collections.abc import Sequence
from typing import Final, final
ASCENSION_SHOP_PRICE_BUMP_DENOM: Final[int]
ASCENSION_SHOP_PRICE_BUMP_LEVEL: Final[int]
ASCENSION_SHOP_PRICE_BUMP_NUMER: Final[int]
CHEST_GOLD_VARIANCE_MAX: Final[float]
CHEST_GOLD_VARIANCE_MIN: Final[float]
CHEST_LARGE_GOLD_BASE: Final[int]
CHEST_LARGE_GOLD_CHANCE: Final[int]
CHEST_MEDIUM_GOLD_BASE: Final[int]
CHEST_MEDIUM_GOLD_CHANCE: Final[int]
CHEST_SMALL_GOLD_BASE: Final[int]
CHEST_SMALL_GOLD_CHANCE: Final[int]
GOLD_BOSS_MAX: Final[int]
GOLD_BOSS_MIN: Final[int]
GOLD_ELITE_MAX: Final[int]
GOLD_ELITE_MIN: Final[int]
GOLD_MONSTER_MAX: Final[int]
GOLD_MONSTER_MIN: Final[int]
HEALTH_START_A6_DENOM: Final[int]
HEALTH_START_A6_NUMER: Final[int]
MAX_GOLD: Final[int]
NEOW_CARD_COUNT: Final[int]
NEOW_GOLD_LARGE: Final[int]
NEOW_GOLD_SMALL: Final[int]
NEOW_POTION_COUNT: Final[int]
SHOP_PRICE_CARD_COMMON: Final[int]
SHOP_PRICE_CARD_MAX: Final[int]
SHOP_PRICE_CARD_RARE: Final[int]
SHOP_PRICE_CARD_UNCOMMON: Final[int]
SHOP_PRICE_CARD_VARIANCE_MAX: Final[float]
SHOP_PRICE_CARD_VARIANCE_MIN: Final[float]
SHOP_PRICE_COLORLESS_DENOM: Final[int]
SHOP_PRICE_COLORLESS_NUMER: Final[int]
SHOP_PRICE_POTION_COMMON: Final[int]
SHOP_PRICE_POTION_MAX: Final[int]
SHOP_PRICE_POTION_RARE: Final[int]
SHOP_PRICE_POTION_UNCOMMON: Final[int]
SHOP_PRICE_RELIC_COMMON: Final[int]
SHOP_PRICE_RELIC_MAX: Final[int]
SHOP_PRICE_RELIC_POTION_VARIANCE_MAX: Final[float]
SHOP_PRICE_RELIC_POTION_VARIANCE_MIN: Final[float]
SHOP_PRICE_RELIC_RARE: Final[int]
SHOP_PRICE_RELIC_SHOP: Final[int]
SHOP_PRICE_RELIC_UNCOMMON: Final[int]
SHOP_PURGE_COST_BASE: Final[int]
SHOP_PURGE_COST_INCREMENT: Final[int]
SHOP_SALE_DIVISOR: Final[int]
SILENT_HP_MAX_A14_DELTA: Final[int]
SILENT_HP_MAX_BASE: Final[int]
STARTING_GOLD: Final[int]
WE_MEET_AGAIN_GOLD_ASK_MAX: Final[int]
WE_MEET_AGAIN_GOLD_ASK_MIN: Final[int]

@final
class Action:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __new__(cls, /, action_type: ActionType, idxs: Sequence[int]) -> Action: ...
    def __repr__(self, /) -> str: ...
    @property
    def action_type(self, /) -> ActionType: ...
    @property
    def idxs(self, /) -> list[int]: ...

@final
class ActionType:
    CardPlay: Final[ActionType]
    ChestOpen: Final[ActionType]
    EffectPendingResolve: Final[ActionType]
    EventOptionSelect: Final[ActionType]
    PickSkip: Final[ActionType]
    PotionDiscard: Final[ActionType]
    PotionUse: Final[ActionType]
    Rest: Final[ActionType]
    RestDig: Final[ActionType]
    RestLift: Final[ActionType]
    RestSmith: Final[ActionType]
    RestToke: Final[ActionType]
    RewardSingingBowl: Final[ActionType]
    RewardTakeCard: Final[ActionType]
    RewardTakeGold: Final[ActionType]
    RewardTakePotion: Final[ActionType]
    RewardTakeRelic: Final[ActionType]
    RoomExit: Final[ActionType]
    RoomSelect: Final[ActionType]
    ShopBuyCard: Final[ActionType]
    ShopBuyPotion: Final[ActionType]
    ShopBuyRelic: Final[ActionType]
    ShopPurge: Final[ActionType]
    TurnEnd: Final[ActionType]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[ActionType]: ...
    @property
    def name(self, /) -> str: ...

@final
class AmountAbsolute:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...

@final
class AmountRange:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def max(self, /) -> int: ...
    @property
    def min(self, /) -> int: ...

@final
class AmountRelative:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def denominator(self, /) -> int: ...
    @property
    def numerator(self, /) -> int: ...

@final
class CandidateFilter:
    Any: Final[CandidateFilter]
    Costed: Final[CandidateFilter]
    KindAttack: Final[CandidateFilter]
    KindPower: Final[CandidateFilter]
    KindSkill: Final[CandidateFilter]
    NotMinion: Final[CandidateFilter]
    NotSource: Final[CandidateFilter]
    Picked: Final[CandidateFilter]
    Purgeable: Final[CandidateFilter]
    PurgeableCurse: Final[CandidateFilter]
    StarterStrike: Final[CandidateFilter]
    StarterUpgradeable: Final[CandidateFilter]
    Transformable: Final[CandidateFilter]
    Upgradeable: Final[CandidateFilter]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[CandidateFilter]: ...

@final
class CandidatePool:
    Character: Final[CandidatePool]
    Deck: Final[CandidatePool]
    Discover: Final[CandidatePool]
    EventRollCard: Final[CandidatePool]
    EventRollPotion: Final[CandidatePool]
    EventRollRelic: Final[CandidatePool]
    Hand: Final[CandidatePool]
    Monsters: Final[CandidatePool]
    PileDiscard: Final[CandidatePool]
    PileDraw: Final[CandidatePool]
    PileExhaust: Final[CandidatePool]
    Source: Final[CandidatePool]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[CandidatePool]: ...

@final
class Card:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def bottled(self, /) -> bool: ...
    @property
    def color(self, /) -> CardColor: ...
    @property
    def cost(self, /) -> int: ...
    @property
    def cost_base(self, /) -> int: ...
    @property
    def cost_kind(self, /) -> CardCostKindFixed |CardCostKindMinusDiscardsThisTurn |CardCostKindGrowsOnDamageInstanceTaken |CardCostKindXCost: ...
    @property
    def cost_override(self, /) -> int |None: ...
    @property
    def cost_override_scope(self, /) -> CostScope |None: ...
    @property
    def effects(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectCardBottle |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectRitualDaggerProc |EffectCardExhaust |EffectCardMove |EffectCardPlayFromDrawTop |EffectGamble |EffectCombatEnd |EffectRelicLose |EffectRewardRollNeowCards |EffectStrengthLoseTemp |EffectMausoleumOpen |EffectKnowingSkullCostBump |EffectJoustBet |EffectRewardRollLibraryCards |EffectRelicGrantPool]: ...
    @property
    def ethereal(self, /) -> bool: ...
    @property
    def exhaust(self, /) -> bool: ...
    @property
    def id(self, /) -> int: ...
    @property
    def innate(self, /) -> bool: ...
    @property
    def kind(self, /) -> CardKind: ...
    @property
    def name(self, /) -> CardName: ...
    @property
    def play_restriction(self, /) -> PlayRestriction: ...
    @property
    def playable(self, /) -> bool: ...
    @property
    def rarity(self, /) -> CardRarity: ...
    @property
    def requires_target(self, /) -> bool: ...
    @property
    def retain(self, /) -> bool: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class CardColor:
    Colorless: Final[CardColor]
    Curse: Final[CardColor]
    Green: Final[CardColor]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[CardColor]: ...

@final
class CardCostKindFixed:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CardCostKindGrowsOnDamageInstanceTaken:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CardCostKindMinusDiscardsThisTurn:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CardCostKindXCost:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def offset(self, /) -> int: ...

@final
class CardKind:
    Attack: Final[CardKind]
    Curse: Final[CardKind]
    Power: Final[CardKind]
    Skill: Final[CardKind]
    Status: Final[CardKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[CardKind]: ...

@final
class CardName:
    AThousandCuts: Final[CardName]
    Accuracy: Final[CardName]
    Acrobatics: Final[CardName]
    Adrenaline: Final[CardName]
    AfterImage: Final[CardName]
    Alchemize: Final[CardName]
    AllOutAttack: Final[CardName]
    Apotheosis: Final[CardName]
    Apparition: Final[CardName]
    AscendersBane: Final[CardName]
    Backflip: Final[CardName]
    Backstab: Final[CardName]
    BandageUp: Final[CardName]
    Bane: Final[CardName]
    Bite: Final[CardName]
    BladeDance: Final[CardName]
    Blind: Final[CardName]
    Blur: Final[CardName]
    BouncingFlask: Final[CardName]
    BulletTime: Final[CardName]
    Burn: Final[CardName]
    Burst: Final[CardName]
    CalculatedGamble: Final[CardName]
    Caltrops: Final[CardName]
    Catalyst: Final[CardName]
    Choke: Final[CardName]
    Chrysalis: Final[CardName]
    CloakAndDagger: Final[CardName]
    Concentrate: Final[CardName]
    CorpseExplosion: Final[CardName]
    CripplingPoison: Final[CardName]
    CurseOfTheBell: Final[CardName]
    DaggerSpray: Final[CardName]
    DaggerThrow: Final[CardName]
    DarkShackles: Final[CardName]
    Dash: Final[CardName]
    Dazed: Final[CardName]
    DeadlyPoison: Final[CardName]
    Decay: Final[CardName]
    DeepBreath: Final[CardName]
    Defend: Final[CardName]
    Deflect: Final[CardName]
    DieDieDie: Final[CardName]
    Discovery: Final[CardName]
    Distraction: Final[CardName]
    DodgeAndRoll: Final[CardName]
    Doppelganger: Final[CardName]
    Doubt: Final[CardName]
    DramaticEntrance: Final[CardName]
    EndlessAgony: Final[CardName]
    Enlightenment: Final[CardName]
    Envenom: Final[CardName]
    EscapePlan: Final[CardName]
    Eviscerate: Final[CardName]
    Expertise: Final[CardName]
    Finesse: Final[CardName]
    Finisher: Final[CardName]
    FlashOfSteel: Final[CardName]
    Flechettes: Final[CardName]
    FlyingKnee: Final[CardName]
    Footwork: Final[CardName]
    Forethought: Final[CardName]
    GlassKnife: Final[CardName]
    GoodInstincts: Final[CardName]
    GrandFinale: Final[CardName]
    HandOfGreed: Final[CardName]
    HeelHook: Final[CardName]
    Impatience: Final[CardName]
    InfiniteBlades: Final[CardName]
    Injury: Final[CardName]
    JackOfAllTrades: Final[CardName]
    Jax: Final[CardName]
    LegSweep: Final[CardName]
    Madness: Final[CardName]
    Magnetism: Final[CardName]
    Malaise: Final[CardName]
    MasterOfStrategy: Final[CardName]
    MasterfulStab: Final[CardName]
    Mayhem: Final[CardName]
    Metamorphosis: Final[CardName]
    MindBlast: Final[CardName]
    Necronomicurse: Final[CardName]
    Neutralize: Final[CardName]
    Nightmare: Final[CardName]
    Normality: Final[CardName]
    NoxiousFumes: Final[CardName]
    Outmaneuver: Final[CardName]
    Pain: Final[CardName]
    Panacea: Final[CardName]
    Panache: Final[CardName]
    PanicButton: Final[CardName]
    Parasite: Final[CardName]
    PhantasmalKiller: Final[CardName]
    PiercingWail: Final[CardName]
    PoisonedStab: Final[CardName]
    Predator: Final[CardName]
    Prepared: Final[CardName]
    Purity: Final[CardName]
    QuickSlash: Final[CardName]
    Reflex: Final[CardName]
    Regret: Final[CardName]
    RiddleWithHoles: Final[CardName]
    RitualDagger: Final[CardName]
    SadisticNature: Final[CardName]
    SecretTechnique: Final[CardName]
    SecretWeapon: Final[CardName]
    Setup: Final[CardName]
    Shame: Final[CardName]
    Shiv: Final[CardName]
    Skewer: Final[CardName]
    Slice: Final[CardName]
    Slimed: Final[CardName]
    SneakyStrike: Final[CardName]
    StormOfSteel: Final[CardName]
    Strike: Final[CardName]
    SuckerPunch: Final[CardName]
    Survivor: Final[CardName]
    SwiftStrike: Final[CardName]
    Tactician: Final[CardName]
    Terror: Final[CardName]
    TheBomb: Final[CardName]
    ThinkingAhead: Final[CardName]
    ToolsOfTheTrade: Final[CardName]
    Transmutation: Final[CardName]
    Trip: Final[CardName]
    Unload: Final[CardName]
    Violence: Final[CardName]
    WellLaidPlans: Final[CardName]
    Wound: Final[CardName]
    WraithForm: Final[CardName]
    Writhe: Final[CardName]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[CardName]: ...

@final
class CardPile:
    Deck: Final[CardPile]
    Discard: Final[CardPile]
    Draw: Final[CardPile]
    Hand: Final[CardPile]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[CardPile]: ...

@final
class CardRarity:
    Basic: Final[CardRarity]
    Common: Final[CardRarity]
    Curse: Final[CardRarity]
    Rare: Final[CardRarity]
    Special: Final[CardRarity]
    Uncommon: Final[CardRarity]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[CardRarity]: ...

@final
class CardTemplate:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def color(self, /) -> CardColor: ...
    @property
    def cost_base(self, /) -> int: ...
    @property
    def cost_kind(self, /) -> CardCostKindFixed |CardCostKindMinusDiscardsThisTurn |CardCostKindGrowsOnDamageInstanceTaken |CardCostKindXCost: ...
    @property
    def effects(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectCardBottle |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectRitualDaggerProc |EffectCardExhaust |EffectCardMove |EffectCardPlayFromDrawTop |EffectGamble |EffectCombatEnd |EffectRelicLose |EffectRewardRollNeowCards |EffectStrengthLoseTemp |EffectMausoleumOpen |EffectKnowingSkullCostBump |EffectJoustBet |EffectRewardRollLibraryCards |EffectRelicGrantPool]: ...
    @property
    def ethereal(self, /) -> bool: ...
    @property
    def exhaust(self, /) -> bool: ...
    @property
    def innate(self, /) -> bool: ...
    @property
    def kind(self, /) -> CardKind: ...
    @property
    def name(self, /) -> CardName: ...
    @property
    def play_restriction(self, /) -> PlayRestriction: ...
    @property
    def rarity(self, /) -> CardRarity: ...
    @property
    def requires_target(self, /) -> bool: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class Character:
    @property
    def block(self, /) -> int: ...
    @property
    def gold(self, /) -> int: ...
    @property
    def health(self, /) -> int: ...
    @property
    def health_max(self, /) -> int: ...
    @property
    def id(self, /) -> int: ...
    @property
    def modifiers(self, /) -> list[Modifier]: ...
    @property
    def name(self, /) -> str: ...

@final
class Chest:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def kind(self, /) -> ChestKind: ...
    @property
    def opened(self, /) -> bool: ...

@final
class ChestKind:
    Large: Final[ChestKind]
    Medium: Final[ChestKind]
    Small: Final[ChestKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[ChestKind]: ...

@final
class Combat:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def bomb_countdown(self, /) -> int: ...
    @property
    def discover(self, /) -> list[Card]: ...
    @property
    def energy(self, /) -> Energy: ...
    @property
    def hand(self, /) -> list[Card]: ...
    @property
    def monsters(self, /) -> list[Monster]: ...
    @property
    def pile_discard(self, /) -> list[Card]: ...
    @property
    def pile_draw(self, /) -> list[Card]: ...
    @property
    def pile_exhaust(self, /) -> list[Card]: ...
    @property
    def pile_stasis(self, /) -> list[Card]: ...

@final
class CostScope:
    Combat: Final[CostScope]
    Turn: Final[CostScope]
    UntilPlayed: Final[CostScope]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[CostScope]: ...

@final
class DeltaSign:
    Gain: Final[DeltaSign]
    Loss: Final[DeltaSign]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[DeltaSign]: ...

@final
class EffectAdventurerSearch:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectBlockGain:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectBonfireOffer:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardAdd:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def card_name(self, /) -> CardName: ...
    @property
    def count(self, /) -> int: ...
    @property
    def pile(self, /) -> CardPile: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class EffectCardAddRandom:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def color(self, /) -> CardColor: ...
    @property
    def cost_zero(self, /) -> CostScope |None: ...
    @property
    def count(self, /) -> int: ...
    @property
    def kind(self, /) -> CardKind |None: ...
    @property
    def pile(self, /) -> CardPile: ...
    @property
    def rarity(self, /) -> CardRarity |None: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class EffectCardBottle:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardDiscard:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardDiscoverPick:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def cost_zero(self, /) -> CostScope |None: ...
    @property
    def pile(self, /) -> CardPile: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardDiscoverRoll:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def color(self, /) -> CardColor: ...
    @property
    def count(self, /) -> int: ...
    @property
    def exclude(self, /) -> list[CardName]: ...
    @property
    def kind(self, /) -> CardKind |None: ...

@final
class EffectCardDraw:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...

@final
class EffectCardDrawIfNoAttacks:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...

@final
class EffectCardDrawUpTo:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...

@final
class EffectCardDuplicate:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardExhaust:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardMove:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def cost_zero(self, /) -> CostScope |None: ...
    @property
    def pile(self, /) -> CardPile: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardNightmarePick:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardPlayFromDrawTop:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectCardPurge:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardRetain:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardSetupPick:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def bottom(self, /) -> bool: ...
    @property
    def free(self, /) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCardTransform:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class EffectCardUpgrade:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectCombatEnd:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def escaped_character(self, /) -> bool: ...

@final
class EffectCombatStart:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectDamageFinisher:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def damage(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectDamageFlechettes:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def damage(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectDamageMindBlast:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectDamagePhysical:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def lifesteal(self, /) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectDamagePhysicalIfPoisoned:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectDistractionAdd:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectEnergyDelta:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def sign(self, /) -> DeltaSign: ...

@final
class EffectEscapePlanCheck:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def block(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectEventAdvanceState:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def delta(self, /) -> int: ...

@final
class EffectEventConsume:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectGamble:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def choose_discards(self, /) -> bool: ...

@final
class EffectGlassKnifeDecay:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def delta(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectGoldDelta:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> AmountAbsolute |AmountRelative |AmountRange: ...
    @property
    def sign(self, /) -> DeltaSign: ...

@final
class EffectHandOfGreedProc:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def gold(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectHealthDelta:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> AmountAbsolute |AmountRelative: ...
    @property
    def sign(self, /) -> DeltaSign: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectHeelHookProc:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectJoustBet:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def on_owner(self, /) -> bool: ...

@final
class EffectKnowingSkullCostBump:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectMausoleumOpen:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectMaxHealthDelta:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> AmountAbsolute |AmountRelative: ...
    @property
    def sign(self, /) -> DeltaSign: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectModifierGain:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def kind(self, /) -> ModifierKind: ...
    @property
    def stacks(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectModifierMultiply:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def factor(self, /) -> int: ...
    @property
    def kind(self, /) -> ModifierKind: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectMonsterSpawn:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self, /) -> MonsterName: ...

@final
class EffectPotionAddRandom:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def limited(self, /) -> bool: ...

@final
class EffectPotionDiscard:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectRelicGrantPool:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def pool(self, /) -> list[RelicName]: ...

@final
class EffectRelicGrantRandom:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def tier(self, /) -> RelicTier |None: ...

@final
class EffectRelicGrantSpecific:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def fallback_circlet(self, /) -> bool: ...
    @property
    def name(self, /) -> RelicName: ...

@final
class EffectRelicLose:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectRewardRollLibraryCards:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectRewardRollNeowCards:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def colorless(self, /) -> bool: ...
    @property
    def rare_only(self, /) -> bool: ...

@final
class EffectRewardRollPotions:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...
    @property
    def uniform(self, /) -> bool: ...

@final
class EffectRitualDaggerProc:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def bump(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectScrapOozeReach:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def advance_on_miss(self, /) -> bool: ...
    @property
    def chance(self, /) -> int: ...

@final
class EffectSetCostOverride:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def only_reduce(self, /) -> bool: ...
    @property
    def random(self, /) -> bool: ...
    @property
    def scope(self, /) -> CostScope: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectShuffleDiscardPileIntoDrawPile:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectSneakyStrikeProc:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def energy(self, /) -> int: ...

@final
class EffectStormOfSteelProc:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class EffectStrengthLoseTemp:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def stacks(self, /) -> int: ...
    @property
    def target(self, /) -> Target: ...

@final
class EffectUnloadDiscard:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class EffectWheelSpin:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class Energy:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def energy_current(self, /) -> int: ...
    @property
    def energy_max(self, /) -> int: ...

@final
class Event:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def consumed(self, /) -> bool: ...
    @property
    def found_gold(self, /) -> bool: ...
    @property
    def found_nothing(self, /) -> bool: ...
    @property
    def found_relic(self, /) -> bool: ...
    @property
    def name(self, /) -> EventName: ...
    @property
    def options(self, /) -> list[list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectCardBottle |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectRitualDaggerProc |EffectCardExhaust |EffectCardMove |EffectCardPlayFromDrawTop |EffectGamble |EffectCombatEnd |EffectRelicLose |EffectRewardRollNeowCards |EffectStrengthLoseTemp |EffectMausoleumOpen |EffectKnowingSkullCostBump |EffectJoustBet |EffectRewardRollLibraryCards |EffectRelicGrantPool]]: ...
    @property
    def roll_cards(self, /) -> list[Card]: ...
    @property
    def roll_potions(self, /) -> list[Potion]: ...
    @property
    def roll_relics(self, /) -> list[Relic]: ...
    @property
    def stage(self, /) -> int: ...

@final
class EventName:
    Addict: Final[EventName]
    BackToBasics: Final[EventName]
    Beggar: Final[EventName]
    BigFish: Final[EventName]
    BonfireSpirits: Final[EventName]
    Colosseum: Final[EventName]
    CursedTome: Final[EventName]
    DeadAdventurer: Final[EventName]
    Designer: Final[EventName]
    DrugDealer: Final[EventName]
    Duplicator: Final[EventName]
    FaceTrader: Final[EventName]
    ForgottenAltar: Final[EventName]
    Ghosts: Final[EventName]
    GoldenIdol: Final[EventName]
    GoldenShrine: Final[EventName]
    KnowingSkull: Final[EventName]
    LivingWall: Final[EventName]
    MaskedBandits: Final[EventName]
    Mushrooms: Final[EventName]
    Neow: Final[EventName]
    Nest: Final[EventName]
    Nloth: Final[EventName]
    OminousForge: Final[EventName]
    Purifier: Final[EventName]
    ScrapOoze: Final[EventName]
    ShiningLight: Final[EventName]
    TheCleric: Final[EventName]
    TheDivineFountain: Final[EventName]
    TheJoust: Final[EventName]
    TheLab: Final[EventName]
    TheLibrary: Final[EventName]
    TheMausoleum: Final[EventName]
    TheSsssserpent: Final[EventName]
    TheWomanInBlue: Final[EventName]
    Transmogrifier: Final[EventName]
    UpgradeShrine: Final[EventName]
    Vampires: Final[EventName]
    WeMeetAgain: Final[EventName]
    WheelOfChange: Final[EventName]
    WingStatue: Final[EventName]
    WorldOfGoop: Final[EventName]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[EventName]: ...

@final
class EventOptionTemplate:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def effects(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectCardBottle |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectRitualDaggerProc |EffectCardExhaust |EffectCardMove |EffectCardPlayFromDrawTop |EffectGamble |EffectCombatEnd |EffectRelicLose |EffectRewardRollNeowCards |EffectStrengthLoseTemp |EffectMausoleumOpen |EffectKnowingSkullCostBump |EffectJoustBet |EffectRewardRollLibraryCards |EffectRelicGrantPool]: ...
    @property
    def event(self, /) -> EventName: ...

@final
class GameEnv:
    ACT_FINAL: Final[int]
    BOMB_FUSE_TURNS: Final[int]
    BOSS_RELIC_REWARD_COUNT: Final[int]
    CARDS_DRAWN_PER_TURN: Final[int]
    CAULDRON_POTION_COUNT: Final[int]
    DISCOVER_PICK_COUNT: Final[int]
    MAP_HEIGHT: Final[int]
    MAP_WIDTH: Final[int]
    MAX_BLOCK: Final[int]
    MAX_CARD_REWARD_ROLL: Final[int]
    MAX_COMBAT_CARD_REWARD: Final[int]
    MAX_EVENT_ROLL_CARDS: Final[int]
    MAX_EVENT_ROLL_POTIONS: Final[int]
    MAX_EVENT_ROLL_RELICS: Final[int]
    MAX_MONSTERS: Final[int]
    MAX_REWARD_CARD_BUNDLES: Final[int]
    MAX_SIZE_HAND: Final[int]
    NIGHTMARE_COPIES: Final[int]
    ORRERY_BUNDLE_COUNT: Final[int]
    POTION_SLOTS_MAX: Final[int]
    REWARD_GOLD_MAX: Final[int]
    SHOP_SLOTS_CARD_TOTAL: Final[int]
    SHOP_SLOTS_POTION: Final[int]
    SHOP_SLOTS_RELIC: Final[int]
    def __new__(cls, /, ascension: int = 0, fast_mode: bool = False, neow: bool = False) -> GameEnv: ...
    def get_legal_actions(self, /) -> list[Action]: ...
    def reset(self, /, seed: int = 42) -> GameState: ...
    def step(self, /, action: Action) -> tuple[GameState, bool]: ...

@final
class GameState:
    @property
    def act(self, /) -> int: ...
    @property
    def ascension(self, /) -> int: ...
    @property
    def character(self, /) -> Character: ...
    @property
    def chest(self, /) -> Chest |None: ...
    @property
    def combat(self, /) -> Combat |None: ...
    @property
    def deck(self, /) -> list[Card]: ...
    @property
    def effect_pending(self, /) -> EffectBonfireOffer |EffectCardBottle |EffectCardDiscard |EffectCardDiscoverPick |EffectCardDuplicate |EffectCardExhaust |EffectCardMove |EffectCardNightmarePick |EffectCardPurge |EffectCardRetain |EffectCardSetupPick |EffectCardTransform |EffectCardUpgrade |EffectRelicLose |None: ...
    @property
    def effect_pending_selected(self, /) -> list[Card]: ...
    @property
    def event(self, /) -> Event |None: ...
    @property
    def game_over(self, /) -> bool: ...
    @property
    def map(self, /) -> Map: ...
    @property
    def potion_slots_max(self, /) -> int: ...
    @property
    def potions(self, /) -> list[Potion |None]: ...
    @property
    def relics(self, /) -> list[Relic]: ...
    @property
    def rest_site(self, /) -> RestSite |None: ...
    @property
    def reward(self, /) -> Reward |None: ...
    @property
    def shop(self, /) -> Shop |None: ...

@final
class Intent:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def damage(self, /) -> int |None: ...
    @property
    def instances(self, /) -> int |None: ...
    @property
    def kind(self, /) -> IntentKind: ...

@final
class IntentKind:
    Attack: Final[IntentKind]
    AttackBlock: Final[IntentKind]
    AttackBuff: Final[IntentKind]
    AttackDebuff: Final[IntentKind]
    Block: Final[IntentKind]
    BlockBuff: Final[IntentKind]
    Buff: Final[IntentKind]
    Debuff: Final[IntentKind]
    DebuffPowerful: Final[IntentKind]
    Escape: Final[IntentKind]
    Sleep: Final[IntentKind]
    Stunned: Final[IntentKind]
    Unknown: Final[IntentKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[IntentKind]: ...

@final
class Map:
    @property
    def boss(self, /) -> MonsterEncounter: ...
    @property
    def identity_hash(self, /) -> int: ...
    @property
    def rooms(self, /) -> list[list[Room |None]]: ...
    @property
    def x_current(self, /) -> int |None: ...
    @property
    def y_current(self, /) -> int |None: ...

@final
class Modifier:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def kind(self, /) -> ModifierKind: ...
    @property
    def stacks(self, /) -> int: ...
    @property
    def stacks_max(self, /) -> int: ...

@final
class ModifierKind:
    Accuracy: Final[ModifierKind]
    AfterImage: Final[ModifierKind]
    Angry: Final[ModifierKind]
    Artifact: Final[ModifierKind]
    Asleep: Final[ModifierKind]
    Barricade: Final[ModifierKind]
    Blur: Final[ModifierKind]
    Buffer: Final[ModifierKind]
    Burst: Final[ModifierKind]
    Choke: Final[ModifierKind]
    Confusion: Final[ModifierKind]
    CorpseExplosion: Final[ModifierKind]
    CurlUp: Final[ModifierKind]
    Dexterity: Final[ModifierKind]
    DoubleDamage: Final[ModifierKind]
    DrawCardNextTurn: Final[ModifierKind]
    DuplicateNextCardPlay: Final[ModifierKind]
    Enrage: Final[ModifierKind]
    Entangled: Final[ModifierKind]
    Envenom: Final[ModifierKind]
    Flight: Final[ModifierKind]
    Frail: Final[ModifierKind]
    Hex: Final[ModifierKind]
    InfiniteBlades: Final[ModifierKind]
    Intangible: Final[ModifierKind]
    LoseDexterity: Final[ModifierKind]
    LoseStrength: Final[ModifierKind]
    Magnetism: Final[ModifierKind]
    Malleable: Final[ModifierKind]
    Mayhem: Final[ModifierKind]
    Metallicize: Final[ModifierKind]
    Minion: Final[ModifierKind]
    ModeShift: Final[ModifierKind]
    NextTurnBlock: Final[ModifierKind]
    NextTurnEnergy: Final[ModifierKind]
    NoBlock: Final[ModifierKind]
    NoDraw: Final[ModifierKind]
    NoxiousFumes: Final[ModifierKind]
    PainfulStabs: Final[ModifierKind]
    Panache: Final[ModifierKind]
    PenNib: Final[ModifierKind]
    Phantasmal: Final[ModifierKind]
    PlatedArmor: Final[ModifierKind]
    Poison: Final[ModifierKind]
    Regeneration: Final[ModifierKind]
    Retain: Final[ModifierKind]
    Ritual: Final[ModifierKind]
    SadisticNature: Final[ModifierKind]
    Shackled: Final[ModifierKind]
    SharpHide: Final[ModifierKind]
    Splittable: Final[ModifierKind]
    SporeCloud: Final[ModifierKind]
    Strength: Final[ModifierKind]
    TheBomb: Final[ModifierKind]
    Thievery: Final[ModifierKind]
    Thorns: Final[ModifierKind]
    ThousandCuts: Final[ModifierKind]
    ToolsOfTheTrade: Final[ModifierKind]
    Vigor: Final[ModifierKind]
    Vulnerable: Final[ModifierKind]
    Weak: Final[ModifierKind]
    WraithForm: Final[ModifierKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def is_buff(self, /) -> bool: ...
    @staticmethod
    def members() -> list[ModifierKind]: ...

@final
class Monster:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def block(self, /) -> int: ...
    @property
    def gold_stolen(self, /) -> int: ...
    @property
    def health(self, /) -> int: ...
    @property
    def health_max(self, /) -> int: ...
    @property
    def id(self, /) -> int: ...
    @property
    def intent(self, /) -> Intent: ...
    @property
    def modifiers(self, /) -> list[Modifier]: ...
    @property
    def name(self, /) -> MonsterName: ...

@final
class MonsterEncounter:
    BlueSlaver: Final[MonsterEncounter]
    BookOfStabbing: Final[MonsterEncounter]
    BronzeAutomaton: Final[MonsterEncounter]
    CenturionAndHealer: Final[MonsterEncounter]
    Champ: Final[MonsterEncounter]
    Chosen: Final[MonsterEncounter]
    ChosenAndByrds: Final[MonsterEncounter]
    Cultist: Final[MonsterEncounter]
    CultistAndChosen: Final[MonsterEncounter]
    ExordiumThugs: Final[MonsterEncounter]
    ExordiumWildlife: Final[MonsterEncounter]
    GremlinGang: Final[MonsterEncounter]
    GremlinLeader: Final[MonsterEncounter]
    GremlinNob: Final[MonsterEncounter]
    Hexaghost: Final[MonsterEncounter]
    JawWorm: Final[MonsterEncounter]
    Lagavulin: Final[MonsterEncounter]
    LargeSlime: Final[MonsterEncounter]
    Looter: Final[MonsterEncounter]
    LotsOfSlimes: Final[MonsterEncounter]
    RedSlaver: Final[MonsterEncounter]
    SentryAndSphere: Final[MonsterEncounter]
    ShelledParasite: Final[MonsterEncounter]
    ShelledParasiteAndFungi: Final[MonsterEncounter]
    Slavers: Final[MonsterEncounter]
    SlimeBoss: Final[MonsterEncounter]
    SmallSlimes: Final[MonsterEncounter]
    SnakePlant: Final[MonsterEncounter]
    Snecko: Final[MonsterEncounter]
    SphericGuardian: Final[MonsterEncounter]
    TheCollector: Final[MonsterEncounter]
    TheGuardian: Final[MonsterEncounter]
    ThreeByrds: Final[MonsterEncounter]
    ThreeCultists: Final[MonsterEncounter]
    ThreeFungiBeasts: Final[MonsterEncounter]
    ThreeLouse: Final[MonsterEncounter]
    ThreeSentries: Final[MonsterEncounter]
    TwoFungiBeasts: Final[MonsterEncounter]
    TwoLouse: Final[MonsterEncounter]
    TwoThieves: Final[MonsterEncounter]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[MonsterEncounter]: ...

@final
class MonsterKind:
    Boss: Final[MonsterKind]
    Elite: Final[MonsterKind]
    Normal: Final[MonsterKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[MonsterKind]: ...

@final
class MonsterName:
    BanditBear: Final[MonsterName]
    BanditLeader: Final[MonsterName]
    BanditPointy: Final[MonsterName]
    BookOfStabbing: Final[MonsterName]
    BronzeAutomaton: Final[MonsterName]
    BronzeOrb: Final[MonsterName]
    Byrd: Final[MonsterName]
    Centurion: Final[MonsterName]
    Champ: Final[MonsterName]
    Chosen: Final[MonsterName]
    Cultist: Final[MonsterName]
    FungiBeast: Final[MonsterName]
    GremlinFat: Final[MonsterName]
    GremlinLeader: Final[MonsterName]
    GremlinNob: Final[MonsterName]
    GremlinThief: Final[MonsterName]
    GremlinTsundere: Final[MonsterName]
    GremlinWarrior: Final[MonsterName]
    GremlinWizard: Final[MonsterName]
    Healer: Final[MonsterName]
    Hexaghost: Final[MonsterName]
    JawWorm: Final[MonsterName]
    Lagavulin: Final[MonsterName]
    Looter: Final[MonsterName]
    LouseDefensive: Final[MonsterName]
    LouseNormal: Final[MonsterName]
    Mugger: Final[MonsterName]
    Sentry: Final[MonsterName]
    ShelledParasite: Final[MonsterName]
    SlaverBlue: Final[MonsterName]
    SlaverRed: Final[MonsterName]
    SlimeAcidLarge: Final[MonsterName]
    SlimeAcidMedium: Final[MonsterName]
    SlimeAcidSmall: Final[MonsterName]
    SlimeBoss: Final[MonsterName]
    SlimeSpikeLarge: Final[MonsterName]
    SlimeSpikeMedium: Final[MonsterName]
    SlimeSpikeSmall: Final[MonsterName]
    SnakePlant: Final[MonsterName]
    Snecko: Final[MonsterName]
    SphericGuardian: Final[MonsterName]
    Taskmaster: Final[MonsterName]
    TheCollector: Final[MonsterName]
    TheGuardian: Final[MonsterName]
    TorchHead: Final[MonsterName]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[MonsterName]: ...

@final
class MonsterTemplate:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def hp_range(self, /) -> tuple[int, int]: ...
    @property
    def kind(self, /) -> MonsterKind: ...
    @property
    def name(self, /) -> MonsterName: ...

@final
class PlayRestriction:
    Always: Final[PlayRestriction]
    DrawPileEmpty: Final[PlayRestriction]
    Never: Final[PlayRestriction]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[PlayRestriction]: ...

@final
class Potion:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def combat_only(self, /) -> bool: ...
    @property
    def effects(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectCardBottle |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectRitualDaggerProc |EffectCardExhaust |EffectCardMove |EffectCardPlayFromDrawTop |EffectGamble |EffectCombatEnd |EffectRelicLose |EffectRewardRollNeowCards |EffectStrengthLoseTemp |EffectMausoleumOpen |EffectKnowingSkullCostBump |EffectJoustBet |EffectRewardRollLibraryCards |EffectRelicGrantPool]: ...
    @property
    def id(self, /) -> int: ...
    @property
    def name(self, /) -> PotionName: ...
    @property
    def rarity(self, /) -> PotionRarity: ...
    @property
    def requires_target(self, /) -> bool: ...

@final
class PotionName:
    Ancient: Final[PotionName]
    Attack: Final[PotionName]
    BlessingOfTheForge: Final[PotionName]
    Block: Final[PotionName]
    Colorless: Final[PotionName]
    Cultist: Final[PotionName]
    Cunning: Final[PotionName]
    Dexterity: Final[PotionName]
    DistilledChaos: Final[PotionName]
    Duplication: Final[PotionName]
    Energy: Final[PotionName]
    EntropicBrew: Final[PotionName]
    EssenceOfSteel: Final[PotionName]
    Explosive: Final[PotionName]
    Fairy: Final[PotionName]
    Fear: Final[PotionName]
    Fire: Final[PotionName]
    FruitJuice: Final[PotionName]
    GamblersBrew: Final[PotionName]
    GhostInAJar: Final[PotionName]
    LiquidBronze: Final[PotionName]
    LiquidMemories: Final[PotionName]
    Poison: Final[PotionName]
    Power: Final[PotionName]
    Regeneration: Final[PotionName]
    Skill: Final[PotionName]
    SmokeBomb: Final[PotionName]
    SneckoOil: Final[PotionName]
    Speed: Final[PotionName]
    Steroid: Final[PotionName]
    Strength: Final[PotionName]
    Swift: Final[PotionName]
    Weak: Final[PotionName]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[PotionName]: ...

@final
class PotionRarity:
    Common: Final[PotionRarity]
    Rare: Final[PotionRarity]
    Uncommon: Final[PotionRarity]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[PotionRarity]: ...

@final
class PotionTemplate:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def combat_only(self, /) -> bool: ...
    @property
    def effects(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectCardBottle |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectRitualDaggerProc |EffectCardExhaust |EffectCardMove |EffectCardPlayFromDrawTop |EffectGamble |EffectCombatEnd |EffectRelicLose |EffectRewardRollNeowCards |EffectStrengthLoseTemp |EffectMausoleumOpen |EffectKnowingSkullCostBump |EffectJoustBet |EffectRewardRollLibraryCards |EffectRelicGrantPool]: ...
    @property
    def name(self, /) -> PotionName: ...
    @property
    def rarity(self, /) -> PotionRarity: ...
    @property
    def requires_target(self, /) -> bool: ...

@final
class Relic:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def counter(self, /) -> int: ...
    @property
    def effects_combat_start(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectCardBottle |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectRitualDaggerProc |EffectCardExhaust |EffectCardMove |EffectCardPlayFromDrawTop |EffectGamble |EffectCombatEnd |EffectRelicLose |EffectRewardRollNeowCards |EffectStrengthLoseTemp |EffectMausoleumOpen |EffectKnowingSkullCostBump |EffectJoustBet |EffectRewardRollLibraryCards |EffectRelicGrantPool]: ...
    @property
    def id(self, /) -> int: ...
    @property
    def name(self, /) -> RelicName: ...
    @property
    def tier(self, /) -> RelicTier: ...
    @property
    def used_up(self, /) -> bool: ...

@final
class RelicName:
    Abacus: Final[RelicName]
    Akabeko: Final[RelicName]
    Anchor: Final[RelicName]
    AncientTeaSet: Final[RelicName]
    ArtOfWar: Final[RelicName]
    Astrolabe: Final[RelicName]
    BagOfMarbles: Final[RelicName]
    BagOfPreparation: Final[RelicName]
    BirdFacedUrn: Final[RelicName]
    BlackStar: Final[RelicName]
    BloodVial: Final[RelicName]
    BloodyIdol: Final[RelicName]
    BlueCandle: Final[RelicName]
    Boot: Final[RelicName]
    BottledFlame: Final[RelicName]
    BottledLightning: Final[RelicName]
    BottledTornado: Final[RelicName]
    BronzeScales: Final[RelicName]
    BustedCrown: Final[RelicName]
    Calipers: Final[RelicName]
    CallingBell: Final[RelicName]
    CaptainsWheel: Final[RelicName]
    Cauldron: Final[RelicName]
    CentennialPuzzle: Final[RelicName]
    CeramicFish: Final[RelicName]
    ChemicalX: Final[RelicName]
    Circlet: Final[RelicName]
    ClockworkSouvenir: Final[RelicName]
    CoffeeDripper: Final[RelicName]
    CultistHeadpiece: Final[RelicName]
    CursedKey: Final[RelicName]
    DarkstonePeriapt: Final[RelicName]
    DeadBranch: Final[RelicName]
    DollysMirror: Final[RelicName]
    DreamCatcher: Final[RelicName]
    DuVuDoll: Final[RelicName]
    Ectoplasm: Final[RelicName]
    EggFrozen: Final[RelicName]
    EggMolten: Final[RelicName]
    EggToxic: Final[RelicName]
    EmptyCage: Final[RelicName]
    Enchiridion: Final[RelicName]
    EternalFeather: Final[RelicName]
    FaceOfCleric: Final[RelicName]
    FossilizedHelix: Final[RelicName]
    FusionHammer: Final[RelicName]
    GamblingChip: Final[RelicName]
    Ginger: Final[RelicName]
    Girya: Final[RelicName]
    GoldenIdol: Final[RelicName]
    GremlinHorn: Final[RelicName]
    GremlinVisage: Final[RelicName]
    HandDrill: Final[RelicName]
    HappyFlower: Final[RelicName]
    HornCleat: Final[RelicName]
    HoveringKite: Final[RelicName]
    IceCream: Final[RelicName]
    IncenseBurner: Final[RelicName]
    InkBottle: Final[RelicName]
    JuzuBracelet: Final[RelicName]
    Kunai: Final[RelicName]
    Lantern: Final[RelicName]
    LeesWaffle: Final[RelicName]
    LetterOpener: Final[RelicName]
    LizardTail: Final[RelicName]
    Mango: Final[RelicName]
    Matryoshka: Final[RelicName]
    MawBank: Final[RelicName]
    MealTicket: Final[RelicName]
    MeatOnTheBone: Final[RelicName]
    MedicalKit: Final[RelicName]
    MembershipCard: Final[RelicName]
    MercuryHourglass: Final[RelicName]
    MummifiedHand: Final[RelicName]
    MutagenicStrength: Final[RelicName]
    Necronomicon: Final[RelicName]
    NeowsLament: Final[RelicName]
    NilrysCodex: Final[RelicName]
    NinjaScroll: Final[RelicName]
    NlothsGift: Final[RelicName]
    NlothsHungryFace: Final[RelicName]
    Nunchaku: Final[RelicName]
    OddMushroom: Final[RelicName]
    OddlySmoothStone: Final[RelicName]
    OldCoin: Final[RelicName]
    Omamori: Final[RelicName]
    OrangePellets: Final[RelicName]
    Orichalcum: Final[RelicName]
    OrnamentalFan: Final[RelicName]
    Orrery: Final[RelicName]
    PandorasBox: Final[RelicName]
    Pantograph: Final[RelicName]
    PaperKrane: Final[RelicName]
    PeacePipe: Final[RelicName]
    Pear: Final[RelicName]
    PenNib: Final[RelicName]
    PhilosopherStone: Final[RelicName]
    Pocketwatch: Final[RelicName]
    PotionBelt: Final[RelicName]
    PrayerWheel: Final[RelicName]
    PreservedInsect: Final[RelicName]
    QuestionCard: Final[RelicName]
    RedMask: Final[RelicName]
    RegalPillow: Final[RelicName]
    RingOfTheSerpent: Final[RelicName]
    RingOfTheSnake: Final[RelicName]
    RunicPyramid: Final[RelicName]
    SacredBark: Final[RelicName]
    Shovel: Final[RelicName]
    Shuriken: Final[RelicName]
    SingingBowl: Final[RelicName]
    SlaversCollar: Final[RelicName]
    SlingOfCourage: Final[RelicName]
    SmilingMask: Final[RelicName]
    SneckoEye: Final[RelicName]
    SneckoSkull: Final[RelicName]
    Sozu: Final[RelicName]
    SpiritPoop: Final[RelicName]
    SsserpentHead: Final[RelicName]
    StoneCalendar: Final[RelicName]
    StrangeSpoon: Final[RelicName]
    Strawberry: Final[RelicName]
    StrikeDummy: Final[RelicName]
    Sundial: Final[RelicName]
    TheCourier: Final[RelicName]
    TheSpecimen: Final[RelicName]
    ThreadAndNeedle: Final[RelicName]
    Tingsha: Final[RelicName]
    TinyChest: Final[RelicName]
    TinyHouse: Final[RelicName]
    Toolbox: Final[RelicName]
    Torii: Final[RelicName]
    ToughBandages: Final[RelicName]
    ToyOrnithopter: Final[RelicName]
    TungstenRod: Final[RelicName]
    Turnip: Final[RelicName]
    TwistedFunnel: Final[RelicName]
    UnceasingTop: Final[RelicName]
    Vajra: Final[RelicName]
    VelvetChoker: Final[RelicName]
    WarPaint: Final[RelicName]
    WarpedTongs: Final[RelicName]
    Whetstone: Final[RelicName]
    WhiteBeastStatue: Final[RelicName]
    WingBoots: Final[RelicName]
    WristBlade: Final[RelicName]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[RelicName]: ...

@final
class RelicTemplate:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def effects_combat_start(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectCardBottle |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectRitualDaggerProc |EffectCardExhaust |EffectCardMove |EffectCardPlayFromDrawTop |EffectGamble |EffectCombatEnd |EffectRelicLose |EffectRewardRollNeowCards |EffectStrengthLoseTemp |EffectMausoleumOpen |EffectKnowingSkullCostBump |EffectJoustBet |EffectRewardRollLibraryCards |EffectRelicGrantPool]: ...
    @property
    def name(self, /) -> RelicName: ...
    @property
    def tier(self, /) -> RelicTier: ...

@final
class RelicTier:
    Boss: Final[RelicTier]
    Common: Final[RelicTier]
    Rare: Final[RelicTier]
    Shop: Final[RelicTier]
    Special: Final[RelicTier]
    Starter: Final[RelicTier]
    Uncommon: Final[RelicTier]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[RelicTier]: ...

@final
class RestSite:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def done(self, /) -> bool: ...

@final
class Reward:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def cards(self, /) -> list[list[Card]]: ...
    @property
    def gold(self, /) -> int |None: ...
    @property
    def potions(self, /) -> list[Potion]: ...
    @property
    def relics(self, /) -> list[Relic]: ...
    @property
    def relics_exclusive(self, /) -> bool: ...

@final
class Room:
    @property
    def edges(self, /) -> list[int]: ...
    @property
    def id(self, /) -> int: ...
    @property
    def room_kind(self, /) -> RoomKind: ...

@final
class RoomKind:
    CombatBoss: Final[RoomKind]
    CombatElite: Final[RoomKind]
    CombatMonster: Final[RoomKind]
    EventRoom: Final[RoomKind]
    RestSite: Final[RoomKind]
    Shop: Final[RoomKind]
    Treasure: Final[RoomKind]
    Unknown: Final[RoomKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def members() -> list[RoomKind]: ...

@final
class SelectionKindAll:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class SelectionKindInput:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...

@final
class SelectionKindInputUpTo:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...

@final
class SelectionKindRandom:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...

@final
class SelectionKindSingle:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class Shop:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def card_prices(self, /) -> list[int]: ...
    @property
    def cards(self, /) -> list[Card]: ...
    @property
    def potion_prices(self, /) -> list[int]: ...
    @property
    def potions(self, /) -> list[Potion]: ...
    @property
    def purge_cost(self, /) -> int: ...
    @property
    def purged(self, /) -> bool: ...
    @property
    def relic_prices(self, /) -> list[int]: ...
    @property
    def relics(self, /) -> list[Relic]: ...

@final
class Target:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def candidate_pool(self, /) -> CandidatePool: ...
    @property
    def filter(self, /) -> CandidateFilter: ...
    @property
    def selection_kind(self, /) -> SelectionKindAll |SelectionKindSingle |SelectionKindRandom |SelectionKindInput |SelectionKindInputUpTo: ...

def get_card_templates() -> list[CardTemplate]: ...
def get_event_option_templates(ascension: int) -> list[EventOptionTemplate]: ...
def get_monster_templates(ascension: int) -> list[MonsterTemplate]: ...
def get_potion_templates() -> list[PotionTemplate]: ...
def get_relic_templates() -> list[RelicTemplate]: ...
