from collections.abc import Sequence
from typing import Final, final

@final
class Action:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __new__(cls, /, action_type: ActionType, idxs: Sequence[int], kind: int |None = None) -> Action: ...
    def __repr__(self, /) -> str: ...
    @property
    def action_type(self, /) -> ActionType: ...
    @property
    def idxs(self, /) -> list[int]: ...
    @property
    def kind(self, /) -> int |None: ...

@final
class ActionType:
    CardDiscard: Final[ActionType]
    CardDiscover: Final[ActionType]
    CardDuplicate: Final[ActionType]
    CardExhaust: Final[ActionType]
    CardMoveToHand: Final[ActionType]
    CardNightmare: Final[ActionType]
    CardPlay: Final[ActionType]
    CardPurge: Final[ActionType]
    CardRetain: Final[ActionType]
    CardSetup: Final[ActionType]
    CardTransform: Final[ActionType]
    CardUpgrade: Final[ActionType]
    ChestOpen: Final[ActionType]
    EventOptionSelect: Final[ActionType]
    PickSkip: Final[ActionType]
    PotionDiscard: Final[ActionType]
    PotionUse: Final[ActionType]
    Rest: Final[ActionType]
    RewardTakeCard: Final[ActionType]
    RewardTakeGold: Final[ActionType]
    RewardTakePotion: Final[ActionType]
    RewardTakeRelic: Final[ActionType]
    RoomExit: Final[ActionType]
    RoomSelect: Final[ActionType]
    ShopBuyCard: Final[ActionType]
    ShopBuyPotion: Final[ActionType]
    ShopBuyRelic: Final[ActionType]
    ShopPurge: Final[ActionType]
    TurnEnd: Final[ActionType]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def name(self, /) -> str: ...

@final
class AmountAbsolute:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...

@final
class AmountEventGoldAsk:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class AmountRange:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def max(self, /) -> int: ...
    @property
    def min(self, /) -> int: ...

@final
class AmountRelative:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def denominator(self, /) -> int: ...
    @property
    def numerator(self, /) -> int: ...

@final
class CandidatePoolCardFilter:
    Any: Final[CandidatePoolCardFilter]
    Attack: Final[CandidatePoolCardFilter]
    Costed: Final[CandidatePoolCardFilter]
    Purgeable: Final[CandidatePoolCardFilter]
    PurgeableCurse: Final[CandidatePoolCardFilter]
    Skill: Final[CandidatePoolCardFilter]
    Transformable: Final[CandidatePoolCardFilter]
    Upgradeable: Final[CandidatePoolCardFilter]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class CandidatePoolCharacter:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CandidatePoolDeck:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def filter(self, /) -> CandidatePoolCardFilter: ...

@final
class CandidatePoolDiscover:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CandidatePoolEventPickCard:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CandidatePoolEventPickPotion:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CandidatePoolHand:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def filter(self, /) -> CandidatePoolCardFilter: ...

@final
class CandidatePoolMonsters:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def filter(self, /) -> CandidatePoolMonstersFilter: ...

@final
class CandidatePoolMonstersFilter:
    All: Final[CandidatePoolMonstersFilter]
    Other: Final[CandidatePoolMonstersFilter]
    Picked: Final[CandidatePoolMonstersFilter]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class CandidatePoolPileDiscard:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CandidatePoolPileDraw:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def filter(self, /) -> CandidatePoolCardFilter: ...

@final
class CandidatePoolPileExhaust:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CandidatePoolSource:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class Card:
    @property
    def color(self, /) -> CardColor: ...
    @property
    def cost(self, /) -> int: ...
    @property
    def cost_base(self, /) -> int: ...
    @property
    def cost_kind(self, /) -> CardCostKindFixed |CardCostKindMinusDiscardsThisTurn |CardCostKindGrowsOnDamageInstanceTaken |CardCostKindXCost: ...
    @property
    def cost_override(self, /) -> int |None: ...
    @property
    def cost_override_scope(self, /) -> CostScope |None: ...
    @property
    def display_name(self, /) -> str: ...
    @property
    def effects(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectModifierRemove |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectCalculatedGamble |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectFaceTrade |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectCardExhaust |EffectCardMove]: ...
    @property
    def ethereal(self, /) -> bool: ...
    @property
    def exhaust(self, /) -> bool: ...
    @property
    def identity_hash(self, /) -> int: ...
    @property
    def innate(self, /) -> bool: ...
    @property
    def kind(self, /) -> CardKind: ...
    @property
    def name(self, /) -> CardName: ...
    @property
    def play_restriction(self, /) -> PlayRestriction: ...
    @property
    def playable(self, /) -> bool: ...
    @property
    def rarity(self, /) -> CardRarity: ...
    @property
    def requires_target(self, /) -> bool: ...
    @property
    def retain(self, /) -> bool: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class CardColor:
    Colorless: Final[CardColor]
    Curse: Final[CardColor]
    Green: Final[CardColor]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class CardCostKindFixed:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CardCostKindGrowsOnDamageInstanceTaken:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CardCostKindMinusDiscardsThisTurn:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class CardCostKindXCost:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def offset(self, /) -> int: ...

@final
class CardKind:
    Attack: Final[CardKind]
    Curse: Final[CardKind]
    Power: Final[CardKind]
    Skill: Final[CardKind]
    Status: Final[CardKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class CardName:
    AThousandCuts: Final[CardName]
    Accuracy: Final[CardName]
    Acrobatics: Final[CardName]
    Adrenaline: Final[CardName]
    AfterImage: Final[CardName]
    Alchemize: Final[CardName]
    AllOutAttack: Final[CardName]
    Apotheosis: Final[CardName]
    Apparition: Final[CardName]
    AscendersBane: Final[CardName]
    Backflip: Final[CardName]
    Backstab: Final[CardName]
    BandageUp: Final[CardName]
    Bane: Final[CardName]
    Bite: Final[CardName]
    BladeDance: Final[CardName]
    Blind: Final[CardName]
    Blur: Final[CardName]
    BouncingFlask: Final[CardName]
    BulletTime: Final[CardName]
    Burn: Final[CardName]
    Burst: Final[CardName]
    CalculatedGamble: Final[CardName]
    Caltrops: Final[CardName]
    Catalyst: Final[CardName]
    Choke: Final[CardName]
    Chrysalis: Final[CardName]
    CloakAndDagger: Final[CardName]
    Concentrate: Final[CardName]
    CorpseExplosion: Final[CardName]
    CripplingPoison: Final[CardName]
    DaggerSpray: Final[CardName]
    DaggerThrow: Final[CardName]
    DarkShackles: Final[CardName]
    Dash: Final[CardName]
    Dazed: Final[CardName]
    DeadlyPoison: Final[CardName]
    Decay: Final[CardName]
    DeepBreath: Final[CardName]
    Defend: Final[CardName]
    Deflect: Final[CardName]
    DieDieDie: Final[CardName]
    Discovery: Final[CardName]
    Distraction: Final[CardName]
    DodgeAndRoll: Final[CardName]
    Doppelganger: Final[CardName]
    Doubt: Final[CardName]
    DramaticEntrance: Final[CardName]
    EndlessAgony: Final[CardName]
    Enlightenment: Final[CardName]
    Envenom: Final[CardName]
    EscapePlan: Final[CardName]
    Eviscerate: Final[CardName]
    Expertise: Final[CardName]
    Finesse: Final[CardName]
    Finisher: Final[CardName]
    FlashOfSteel: Final[CardName]
    Flechettes: Final[CardName]
    FlyingKnee: Final[CardName]
    Footwork: Final[CardName]
    Forethought: Final[CardName]
    GlassKnife: Final[CardName]
    GoodInstincts: Final[CardName]
    GrandFinale: Final[CardName]
    HandOfGreed: Final[CardName]
    HeelHook: Final[CardName]
    Impatience: Final[CardName]
    InfiniteBlades: Final[CardName]
    Injury: Final[CardName]
    JackOfAllTrades: Final[CardName]
    Jax: Final[CardName]
    LegSweep: Final[CardName]
    Madness: Final[CardName]
    Magnetism: Final[CardName]
    Malaise: Final[CardName]
    MasterOfStrategy: Final[CardName]
    MasterfulStab: Final[CardName]
    Mayhem: Final[CardName]
    Metamorphosis: Final[CardName]
    MindBlast: Final[CardName]
    Neutralize: Final[CardName]
    Nightmare: Final[CardName]
    Normality: Final[CardName]
    NoxiousFumes: Final[CardName]
    Outmaneuver: Final[CardName]
    Pain: Final[CardName]
    Panacea: Final[CardName]
    Panache: Final[CardName]
    PanicButton: Final[CardName]
    Parasite: Final[CardName]
    PhantasmalKiller: Final[CardName]
    PiercingWail: Final[CardName]
    PoisonedStab: Final[CardName]
    Predator: Final[CardName]
    Prepared: Final[CardName]
    Purity: Final[CardName]
    QuickSlash: Final[CardName]
    Reflex: Final[CardName]
    Regret: Final[CardName]
    RiddleWithHoles: Final[CardName]
    SadisticNature: Final[CardName]
    SecretTechnique: Final[CardName]
    SecretWeapon: Final[CardName]
    Setup: Final[CardName]
    Shame: Final[CardName]
    Shiv: Final[CardName]
    Skewer: Final[CardName]
    Slice: Final[CardName]
    Slimed: Final[CardName]
    SneakyStrike: Final[CardName]
    StormOfSteel: Final[CardName]
    Strike: Final[CardName]
    SuckerPunch: Final[CardName]
    Survivor: Final[CardName]
    SwiftStrike: Final[CardName]
    Tactician: Final[CardName]
    Terror: Final[CardName]
    TheBomb: Final[CardName]
    ThinkingAhead: Final[CardName]
    ToolsOfTheTrade: Final[CardName]
    Transmutation: Final[CardName]
    Trip: Final[CardName]
    Unload: Final[CardName]
    Violence: Final[CardName]
    WellLaidPlans: Final[CardName]
    WraithForm: Final[CardName]
    Writhe: Final[CardName]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class CardPile:
    Deck: Final[CardPile]
    Discard: Final[CardPile]
    Draw: Final[CardPile]
    Hand: Final[CardPile]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class CardRarity:
    Basic: Final[CardRarity]
    Common: Final[CardRarity]
    Curse: Final[CardRarity]
    Rare: Final[CardRarity]
    Special: Final[CardRarity]
    Uncommon: Final[CardRarity]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class Character:
    def __new__(cls, /, name: str, health: int, health_max: int, block: int, modifiers: Sequence[Modifier], gold: int) -> Character: ...
    @property
    def block(self, /) -> int: ...
    @property
    def gold(self, /) -> int: ...
    @property
    def health(self, /) -> int: ...
    @property
    def health_max(self, /) -> int: ...
    @property
    def modifiers(self, /) -> list[Modifier]: ...
    @property
    def name(self, /) -> str: ...

@final
class CostScope:
    Combat: Final[CostScope]
    Turn: Final[CostScope]
    UntilPlayed: Final[CostScope]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class DeltaSign:
    Gain: Final[DeltaSign]
    Loss: Final[DeltaSign]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class EffectAdventurerSearch:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectBlockGain:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectBonfireOffer:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCalculatedGamble:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardAdd:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def card_name(self, /) -> str: ...
    @property
    def count(self, /) -> int: ...
    @property
    def pile(self, /) -> CardPile: ...
    @property
    def target(self, /) -> Target |None: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class EffectCardAddRandom:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def color(self, /) -> CardColor: ...
    @property
    def cost_zero(self, /) -> CostScope |None: ...
    @property
    def count(self, /) -> int: ...
    @property
    def kind(self, /) -> CardKind |None: ...
    @property
    def pile(self, /) -> CardPile: ...
    @property
    def target(self, /) -> Target |None: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class EffectCardDiscard:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardDiscoverPick:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardDiscoverRoll:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...
    @property
    def kind(self, /) -> CardKind |None: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardDraw:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardDrawIfNoAttacks:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardDrawUpTo:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardDuplicate:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardExhaust:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardMove:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def pile(self, /) -> CardPile: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardNightmarePick:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardPurge:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardRetain:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardSetupPick:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def bottom(self, /) -> bool: ...
    @property
    def free(self, /) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardTransform:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCardUpgrade:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectCombatStart:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def event_gold(self, /) -> AmountAbsolute |AmountRelative |AmountRange |AmountEventGoldAsk |None: ...
    @property
    def event_relic(self, /) -> RelicName |None: ...
    @property
    def event_relic_roll(self, /) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectDamageFinisher:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def damage(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectDamageFlechettes:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def damage(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectDamageMindBlast:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectDamagePhysical:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectDamagePhysicalIfPoisoned:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectDistractionAdd:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectEnergyDelta:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def sign(self, /) -> DeltaSign: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectEscapePlanCheck:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def block(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectEventAdvanceState:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def delta(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectEventConsume:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectFaceTrade:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectGlassKnifeDecay:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def delta(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectGoldDelta:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> AmountAbsolute |AmountRelative |AmountRange |AmountEventGoldAsk: ...
    @property
    def sign(self, /) -> DeltaSign: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectHandOfGreedProc:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def gold(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectHealthDelta:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> AmountAbsolute |AmountRelative |AmountRange |AmountEventGoldAsk: ...
    @property
    def sign(self, /) -> DeltaSign: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectHeelHookProc:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectMaxHealthDelta:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> AmountAbsolute |AmountRelative |AmountRange |AmountEventGoldAsk: ...
    @property
    def sign(self, /) -> DeltaSign: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectModifierGain:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def kind(self, /) -> ModifierKind: ...
    @property
    def stacks(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectModifierMultiply:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def factor(self, /) -> int: ...
    @property
    def kind(self, /) -> ModifierKind: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectModifierRemove:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def kind(self, /) -> ModifierKind: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectMonsterSpawn:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self, /) -> MonsterName: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectPotionAddRandom:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def limited(self, /) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectPotionDiscard:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectRelicGrantRandom:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectRelicGrantSpecific:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def fallback_circlet(self, /) -> bool: ...
    @property
    def name(self, /) -> RelicName: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectRewardRollPotions:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectScrapOozeReach:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def advance_on_miss(self, /) -> bool: ...
    @property
    def chance(self, /) -> int: ...
    @property
    def dmg(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectSetCostOverride:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def amount(self, /) -> int: ...
    @property
    def only_reduce(self, /) -> bool: ...
    @property
    def scope(self, /) -> CostScope: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectShuffleDiscardPileIntoDrawPile:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectSneakyStrikeProc:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def energy(self, /) -> int: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectStormOfSteelProc:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...
    @property
    def upgraded(self, /) -> bool: ...

@final
class EffectUnloadDiscard:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class EffectWheelSpin:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def target(self, /) -> Target |None: ...

@final
class Energy:
    def __new__(cls, /, energy_current: int, energy_max: int) -> Energy: ...
    @property
    def energy_current(self, /) -> int: ...
    @property
    def energy_max(self, /) -> int: ...

@final
class EventKindBigFish: ...

@final
class EventKindBonfireSpirits: ...

@final
class EventKindDeadAdventurer:
    @property
    def found_gold(self, /) -> bool: ...
    @property
    def found_nothing(self, /) -> bool: ...
    @property
    def found_relic(self, /) -> bool: ...
    @property
    def searches(self, /) -> int: ...

@final
class EventKindDuplicator: ...

@final
class EventKindFaceTrader: ...

@final
class EventKindGoldenIdol:
    @property
    def stage(self, /) -> int: ...

@final
class EventKindGoldenShrine: ...

@final
class EventKindLivingWall: ...

@final
class EventKindMushrooms: ...

@final
class EventKindOminousForge: ...

@final
class EventKindPurifier: ...

@final
class EventKindScrapOoze:
    @property
    def attempts(self, /) -> int: ...

@final
class EventKindShiningLight: ...

@final
class EventKindTheCleric: ...

@final
class EventKindTheDivineFountain: ...

@final
class EventKindTheLab: ...

@final
class EventKindTheSsssserpent: ...

@final
class EventKindTheWomanInBlue: ...

@final
class EventKindTransmogrifier: ...

@final
class EventKindUpgradeShrine: ...

@final
class EventKindWeMeetAgain:
    @property
    def gold_ask(self, /) -> int |None: ...
    @property
    def pick_card(self, /) -> Card |None: ...
    @property
    def pick_potion(self, /) -> Potion |None: ...

@final
class EventKindWheelOfChange: ...

@final
class EventKindWingStatue: ...

@final
class EventKindWorldOfGoop: ...

@final
class GameEnv:
    CARDS_DRAWN_PER_TURN: Final[int]
    MAP_HEIGHT: Final[int]
    MAP_WIDTH: Final[int]
    MAX_BLOCK: Final[int]
    MAX_COMBAT_CARD_REWARD: Final[int]
    MAX_MONSTERS: Final[int]
    MAX_SIZE_HAND: Final[int]
    NIGHTMARE_COPIES: Final[int]
    def __new__(cls, /, ascension: int = 0, fast_mode: bool = False) -> GameEnv: ...
    def get_legal_actions(self, /) -> list[Action]: ...
    def reset(self, /, seed: int = 42) -> GameState: ...
    def step(self, /, action: Action) -> tuple[GameState, bool]: ...

@final
class GameState:
    @property
    def ascension(self, /) -> int: ...
    @property
    def character(self, /) -> Character: ...
    @property
    def deck(self, /) -> list[Card]: ...
    @property
    def game_over(self, /) -> bool: ...
    @property
    def map(self, /) -> Map: ...
    @property
    def mode(self, /) -> ModeMap |ModeRestSite |ModeChest |ModeChestOpened |ModeCombatEnded |ModeCombat |ModeReward |ModeShop |ModeEvent: ...
    @property
    def pending(self, /) -> EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectModifierRemove |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectCalculatedGamble |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectFaceTrade |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectCardExhaust |EffectCardMove |None: ...
    @property
    def potion_slots_max(self, /) -> int: ...
    @property
    def potions(self, /) -> list[Potion |None]: ...
    @property
    def relics(self, /) -> list[Relic]: ...

@final
class Intent:
    def __new__(cls, /, kind: IntentKind, damage: int |None, instances: int |None) -> Intent: ...
    @property
    def damage(self, /) -> int |None: ...
    @property
    def instances(self, /) -> int |None: ...
    @property
    def kind(self, /) -> IntentKind: ...

@final
class IntentKind:
    Attack: Final[IntentKind]
    AttackBlock: Final[IntentKind]
    AttackBuff: Final[IntentKind]
    AttackDebuff: Final[IntentKind]
    Block: Final[IntentKind]
    BlockBuff: Final[IntentKind]
    Buff: Final[IntentKind]
    Debuff: Final[IntentKind]
    DebuffPowerful: Final[IntentKind]
    Escape: Final[IntentKind]
    Sleep: Final[IntentKind]
    Stunned: Final[IntentKind]
    Unknown: Final[IntentKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class Map:
    def __new__(cls, /, rooms: Sequence[Sequence[Room |None]], y_current: int |None, x_current: int |None, boss: MonsterEncounter, identity_hash: int) -> Map: ...
    @property
    def boss(self, /) -> MonsterEncounter: ...
    @property
    def identity_hash(self, /) -> int: ...
    @property
    def rooms(self, /) -> list[list[Room |None]]: ...
    @property
    def x_current(self, /) -> int |None: ...
    @property
    def y_current(self, /) -> int |None: ...

@final
class ModeChest: ...

@final
class ModeChestOpened: ...

@final
class ModeCombat:
    @property
    def bomb_countdown(self, /) -> int: ...
    @property
    def discover(self, /) -> list[Card]: ...
    @property
    def energy(self, /) -> Energy: ...
    @property
    def hand(self, /) -> list[Card]: ...
    @property
    def monsters(self, /) -> list[Monster]: ...
    @property
    def pile_discard(self, /) -> list[Card]: ...
    @property
    def pile_draw(self, /) -> list[Card]: ...
    @property
    def pile_exhaust(self, /) -> list[Card]: ...

@final
class ModeCombatEnded: ...

@final
class ModeEvent:
    @property
    def consumed(self, /) -> bool: ...
    @property
    def kind(self, /) -> EventKindBigFish |EventKindTheCleric |EventKindDuplicator |EventKindGoldenShrine |EventKindWingStatue |EventKindWorldOfGoop |EventKindLivingWall |EventKindPurifier |EventKindShiningLight |EventKindTheSsssserpent |EventKindTransmogrifier |EventKindUpgradeShrine |EventKindTheDivineFountain |EventKindTheLab |EventKindTheWomanInBlue |EventKindWheelOfChange |EventKindBonfireSpirits |EventKindOminousForge |EventKindFaceTrader |EventKindMushrooms |EventKindGoldenIdol |EventKindScrapOoze |EventKindWeMeetAgain |EventKindDeadAdventurer: ...
    @property
    def options(self, /) -> list[list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectModifierRemove |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectCalculatedGamble |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectFaceTrade |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectCardExhaust |EffectCardMove]]: ...

@final
class ModeMap: ...

@final
class ModeRestSite: ...

@final
class ModeReward:
    @property
    def cards(self, /) -> list[Card]: ...
    @property
    def gold(self, /) -> int |None: ...
    @property
    def potions(self, /) -> list[Potion]: ...
    @property
    def relic(self, /) -> Relic |None: ...

@final
class ModeShop:
    @property
    def card_prices(self, /) -> list[int]: ...
    @property
    def cards(self, /) -> list[Card]: ...
    @property
    def potion_prices(self, /) -> list[int]: ...
    @property
    def potions(self, /) -> list[Potion]: ...
    @property
    def purge_cost(self, /) -> int: ...
    @property
    def relic_prices(self, /) -> list[int]: ...
    @property
    def relics(self, /) -> list[Relic]: ...

@final
class Modifier:
    def __new__(cls, /, kind: ModifierKind, stacks: int, stacks_max: int) -> Modifier: ...
    @property
    def kind(self, /) -> ModifierKind: ...
    @property
    def stacks(self, /) -> int: ...
    @property
    def stacks_max(self, /) -> int: ...

@final
class ModifierKind:
    Accuracy: Final[ModifierKind]
    AfterImage: Final[ModifierKind]
    Angry: Final[ModifierKind]
    Artifact: Final[ModifierKind]
    Asleep: Final[ModifierKind]
    Blur: Final[ModifierKind]
    Buffer: Final[ModifierKind]
    Burst: Final[ModifierKind]
    Choke: Final[ModifierKind]
    CorpseExplosion: Final[ModifierKind]
    CurlUp: Final[ModifierKind]
    Dexterity: Final[ModifierKind]
    DoubleDamage: Final[ModifierKind]
    DrawCardNextTurn: Final[ModifierKind]
    Enrage: Final[ModifierKind]
    Entangled: Final[ModifierKind]
    Envenom: Final[ModifierKind]
    Frail: Final[ModifierKind]
    InfiniteBlades: Final[ModifierKind]
    Intangible: Final[ModifierKind]
    Magnetism: Final[ModifierKind]
    Mayhem: Final[ModifierKind]
    Metallicize: Final[ModifierKind]
    ModeShift: Final[ModifierKind]
    NextTurnBlock: Final[ModifierKind]
    NextTurnEnergy: Final[ModifierKind]
    NoBlock: Final[ModifierKind]
    NoDraw: Final[ModifierKind]
    NoxiousFumes: Final[ModifierKind]
    Panache: Final[ModifierKind]
    PenNib: Final[ModifierKind]
    Phantasmal: Final[ModifierKind]
    PlatedArmor: Final[ModifierKind]
    Poison: Final[ModifierKind]
    Retain: Final[ModifierKind]
    Ritual: Final[ModifierKind]
    SadisticNature: Final[ModifierKind]
    Shackled: Final[ModifierKind]
    SharpHide: Final[ModifierKind]
    Splittable: Final[ModifierKind]
    SporeCloud: Final[ModifierKind]
    Strength: Final[ModifierKind]
    TheBomb: Final[ModifierKind]
    Thievery: Final[ModifierKind]
    Thorns: Final[ModifierKind]
    ThousandCuts: Final[ModifierKind]
    ToolsOfTheTrade: Final[ModifierKind]
    Vigor: Final[ModifierKind]
    Vulnerable: Final[ModifierKind]
    Weak: Final[ModifierKind]
    WraithForm: Final[ModifierKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def is_buff(self, /) -> bool: ...

@final
class Monster:
    def __new__(cls, /, name: MonsterName, display_name: str, health: int, health_max: int, block: int, modifiers: Sequence[Modifier], intent: Intent) -> Monster: ...
    @property
    def block(self, /) -> int: ...
    @property
    def display_name(self, /) -> str: ...
    @property
    def health(self, /) -> int: ...
    @property
    def health_max(self, /) -> int: ...
    @property
    def intent(self, /) -> Intent: ...
    @property
    def modifiers(self, /) -> list[Modifier]: ...
    @property
    def name(self, /) -> MonsterName: ...

@final
class MonsterEncounter:
    BlueSlaver: Final[MonsterEncounter]
    Cultist: Final[MonsterEncounter]
    ExordiumThugs: Final[MonsterEncounter]
    ExordiumWildlife: Final[MonsterEncounter]
    GremlinGang: Final[MonsterEncounter]
    GremlinNob: Final[MonsterEncounter]
    Hexaghost: Final[MonsterEncounter]
    JawWorm: Final[MonsterEncounter]
    Lagavulin: Final[MonsterEncounter]
    LargeSlime: Final[MonsterEncounter]
    Looter: Final[MonsterEncounter]
    LotsOfSlimes: Final[MonsterEncounter]
    RedSlaver: Final[MonsterEncounter]
    SlimeBoss: Final[MonsterEncounter]
    SmallSlimes: Final[MonsterEncounter]
    TheGuardian: Final[MonsterEncounter]
    ThreeFungiBeasts: Final[MonsterEncounter]
    ThreeLouse: Final[MonsterEncounter]
    ThreeSentries: Final[MonsterEncounter]
    TwoFungiBeasts: Final[MonsterEncounter]
    TwoLouse: Final[MonsterEncounter]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class MonsterName:
    Cultist: Final[MonsterName]
    FungiBeast: Final[MonsterName]
    GremlinFat: Final[MonsterName]
    GremlinNob: Final[MonsterName]
    GremlinThief: Final[MonsterName]
    GremlinTsundere: Final[MonsterName]
    GremlinWarrior: Final[MonsterName]
    GremlinWizard: Final[MonsterName]
    Hexaghost: Final[MonsterName]
    JawWorm: Final[MonsterName]
    Lagavulin: Final[MonsterName]
    Looter: Final[MonsterName]
    LouseDefensive: Final[MonsterName]
    LouseNormal: Final[MonsterName]
    Sentry: Final[MonsterName]
    SlaverBlue: Final[MonsterName]
    SlaverRed: Final[MonsterName]
    SlimeAcidLarge: Final[MonsterName]
    SlimeAcidMedium: Final[MonsterName]
    SlimeAcidSmall: Final[MonsterName]
    SlimeBoss: Final[MonsterName]
    SlimeSpikeLarge: Final[MonsterName]
    SlimeSpikeMedium: Final[MonsterName]
    SlimeSpikeSmall: Final[MonsterName]
    TheGuardian: Final[MonsterName]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class PlayRestriction:
    Always: Final[PlayRestriction]
    DrawPileEmpty: Final[PlayRestriction]
    Never: Final[PlayRestriction]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class Potion:
    @property
    def combat_only(self, /) -> bool: ...
    @property
    def effects(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectModifierRemove |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectCalculatedGamble |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectFaceTrade |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectCardExhaust |EffectCardMove]: ...
    @property
    def name(self, /) -> PotionName: ...
    @property
    def rarity(self, /) -> PotionRarity: ...
    @property
    def requires_target(self, /) -> bool: ...

@final
class PotionName:
    AttackPotion: Final[PotionName]
    BlockPotion: Final[PotionName]
    DexterityPotion: Final[PotionName]
    EnergyPotion: Final[PotionName]
    ExplosivePotion: Final[PotionName]
    FearPotion: Final[PotionName]
    FirePotion: Final[PotionName]
    FruitJuice: Final[PotionName]
    PoisonPotion: Final[PotionName]
    PowerPotion: Final[PotionName]
    SkillPotion: Final[PotionName]
    StrengthPotion: Final[PotionName]
    SwiftPotion: Final[PotionName]
    WeakPotion: Final[PotionName]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class PotionRarity:
    Common: Final[PotionRarity]
    Rare: Final[PotionRarity]
    Uncommon: Final[PotionRarity]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class Relic:
    @property
    def counter(self, /) -> int: ...
    @property
    def effects_on_combat_start(self, /) -> list[EffectDamagePhysical |EffectDamagePhysicalIfPoisoned |EffectHeelHookProc |EffectEscapePlanCheck |EffectGlassKnifeDecay |EffectCardSetupPick |EffectCardNightmarePick |EffectDistractionAdd |EffectSetCostOverride |EffectDamageFinisher |EffectDamageFlechettes |EffectUnloadDiscard |EffectStormOfSteelProc |EffectSneakyStrikeProc |EffectBlockGain |EffectModifierGain |EffectModifierMultiply |EffectModifierRemove |EffectEnergyDelta |EffectCardAdd |EffectCardDraw |EffectCardDrawUpTo |EffectCardDiscard |EffectCardRetain |EffectDamageMindBlast |EffectShuffleDiscardPileIntoDrawPile |EffectCalculatedGamble |EffectMaxHealthDelta |EffectHealthDelta |EffectPotionAddRandom |EffectPotionDiscard |EffectRewardRollPotions |EffectCardDiscoverRoll |EffectGoldDelta |EffectRelicGrantRandom |EffectWheelSpin |EffectBonfireOffer |EffectFaceTrade |EffectMonsterSpawn |EffectCombatStart |EffectAdventurerSearch |EffectRelicGrantSpecific |EffectEventAdvanceState |EffectScrapOozeReach |EffectEventConsume |EffectCardDiscoverPick |EffectCardPurge |EffectCardUpgrade |EffectCardDuplicate |EffectCardTransform |EffectCardAddRandom |EffectCardDrawIfNoAttacks |EffectHandOfGreedProc |EffectCardExhaust |EffectCardMove]: ...
    @property
    def name(self, /) -> RelicName: ...
    @property
    def tier(self, /) -> RelicTier: ...
    @property
    def used_up(self, /) -> bool: ...

@final
class RelicName:
    Abacus: Final[RelicName]
    Akabeko: Final[RelicName]
    Anchor: Final[RelicName]
    AncientTeaSet: Final[RelicName]
    ArtOfWar: Final[RelicName]
    BagOfMarbles: Final[RelicName]
    BagOfPreparation: Final[RelicName]
    BirdFacedUrn: Final[RelicName]
    BloodVial: Final[RelicName]
    BlueCandle: Final[RelicName]
    Boot: Final[RelicName]
    BronzeScales: Final[RelicName]
    Calipers: Final[RelicName]
    CaptainsWheel: Final[RelicName]
    CentennialPuzzle: Final[RelicName]
    CeramicFish: Final[RelicName]
    ChemicalX: Final[RelicName]
    Circlet: Final[RelicName]
    ClockworkSouvenir: Final[RelicName]
    CultistHeadpiece: Final[RelicName]
    DarkstonePeriapt: Final[RelicName]
    DeadBranch: Final[RelicName]
    DollysMirror: Final[RelicName]
    DuVuDoll: Final[RelicName]
    EmptyCage: Final[RelicName]
    EternalFeather: Final[RelicName]
    FaceOfCleric: Final[RelicName]
    FossilizedHelix: Final[RelicName]
    FrozenEgg: Final[RelicName]
    Ginger: Final[RelicName]
    GoldenIdol: Final[RelicName]
    GremlinHorn: Final[RelicName]
    GremlinVisage: Final[RelicName]
    HandDrill: Final[RelicName]
    HappyFlower: Final[RelicName]
    HornCleat: Final[RelicName]
    IceCream: Final[RelicName]
    IncenseBurner: Final[RelicName]
    InkBottle: Final[RelicName]
    JuzuBracelet: Final[RelicName]
    Kunai: Final[RelicName]
    Lantern: Final[RelicName]
    LeesWaffle: Final[RelicName]
    LetterOpener: Final[RelicName]
    LizardTail: Final[RelicName]
    Mango: Final[RelicName]
    MawBank: Final[RelicName]
    MealTicket: Final[RelicName]
    MeatOnTheBone: Final[RelicName]
    MedicalKit: Final[RelicName]
    MercuryHourglass: Final[RelicName]
    MoltenEgg: Final[RelicName]
    MummifiedHand: Final[RelicName]
    NinjaScroll: Final[RelicName]
    NlothsHungryFace: Final[RelicName]
    Nunchaku: Final[RelicName]
    OddMushroom: Final[RelicName]
    OddlySmoothStone: Final[RelicName]
    OldCoin: Final[RelicName]
    Omamori: Final[RelicName]
    OrangePellets: Final[RelicName]
    Orichalcum: Final[RelicName]
    OrnamentalFan: Final[RelicName]
    PandorasBox: Final[RelicName]
    Pantograph: Final[RelicName]
    PaperKrane: Final[RelicName]
    Pear: Final[RelicName]
    PenNib: Final[RelicName]
    Pocketwatch: Final[RelicName]
    PotionBelt: Final[RelicName]
    PreservedInsect: Final[RelicName]
    RedMask: Final[RelicName]
    RegalPillow: Final[RelicName]
    Shuriken: Final[RelicName]
    SlingOfCourage: Final[RelicName]
    SmilingMask: Final[RelicName]
    SnakeRing: Final[RelicName]
    SneckoSkull: Final[RelicName]
    SpiritPoop: Final[RelicName]
    SsserpentHead: Final[RelicName]
    StoneCalendar: Final[RelicName]
    StrangeSpoon: Final[RelicName]
    Strawberry: Final[RelicName]
    StrikeDummy: Final[RelicName]
    Sundial: Final[RelicName]
    TheSpecimen: Final[RelicName]
    ThreadAndNeedle: Final[RelicName]
    Tingsha: Final[RelicName]
    TinyChest: Final[RelicName]
    Torii: Final[RelicName]
    ToughBandages: Final[RelicName]
    ToxicEgg: Final[RelicName]
    ToyOrnithopter: Final[RelicName]
    TungstenRod: Final[RelicName]
    Turnip: Final[RelicName]
    TwistedFunnel: Final[RelicName]
    UnceasingTop: Final[RelicName]
    Vajra: Final[RelicName]
    WarPaint: Final[RelicName]
    WarpedTongs: Final[RelicName]
    Whetstone: Final[RelicName]
    WhiteBeastStatue: Final[RelicName]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class RelicTier:
    Boss: Final[RelicTier]
    Common: Final[RelicTier]
    Rare: Final[RelicTier]
    Shop: Final[RelicTier]
    Special: Final[RelicTier]
    Starter: Final[RelicTier]
    Uncommon: Final[RelicTier]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class Room:
    def __new__(cls, /, room_kind: RoomKind, edges: Sequence[int], chest_opened: bool) -> Room: ...
    @property
    def chest_opened(self, /) -> bool: ...
    @property
    def edges(self, /) -> list[int]: ...
    @property
    def room_kind(self, /) -> RoomKind: ...

@final
class RoomKind:
    CombatBoss: Final[RoomKind]
    CombatElite: Final[RoomKind]
    CombatMonster: Final[RoomKind]
    EventRoom: Final[RoomKind]
    RestSite: Final[RoomKind]
    Shop: Final[RoomKind]
    Treasure: Final[RoomKind]
    Unknown: Final[RoomKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class SelectionKindAll:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class SelectionKindInput:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...

@final
class SelectionKindInputUpTo:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...

@final
class SelectionKindRandom:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def count(self, /) -> int: ...

@final
class SelectionKindSingle:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...

@final
class Target:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def candidate_pool(self, /) -> CandidatePoolHand |CandidatePoolCharacter |CandidatePoolMonsters |CandidatePoolSource |CandidatePoolDiscover |CandidatePoolDeck |CandidatePoolEventPickCard |CandidatePoolEventPickPotion |CandidatePoolPileDraw |CandidatePoolPileDiscard |CandidatePoolPileExhaust: ...
    @property
    def selection_kind(self, /) -> SelectionKindAll |SelectionKindSingle |SelectionKindRandom |SelectionKindInput |SelectionKindInputUpTo: ...
