use pyo3::prelude::*;

use crate::entity::Entity;
use crate::types::RelicName;
use crate::types::RelicTier;

use super::effect::PyEffect;
use super::effect::snapshot_effect;

#[pyclass(
    skip_from_py_object,
    eq,
    eq_int,
    frozen,
    name = "RelicName",
    module = "slai.slai"
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PyRelicName {
    SnakeRing,
    Akabeko,
    Anchor,
    BagOfMarbles,
    BagOfPreparation,
    BloodVial,
    BronzeScales,
    Kunai,
    NinjaScroll,
    OddlySmoothStone,
    Shuriken,
    ThreadAndNeedle,
    TwistedFunnel,
    Vajra,
    Circlet,
    GoldenIdol,
    Lantern,
    ClockworkSouvenir,
    GremlinVisage,
    RedMask,
    Nunchaku,
    InkBottle,
    LetterOpener,
    OrnamentalFan,
    BirdFacedUrn,
    MummifiedHand,
    OrangePellets,
    StrangeSpoon,
    ChemicalX,
    ArtOfWar,
    Orichalcum,
    Pocketwatch,
    StoneCalendar,
    Abacus,
    Sundial,
    WhiteBeastStatue,
    DollysMirror,
    LeesWaffle,
    HappyFlower,
    IncenseBurner,
    MercuryHourglass,
    HornCleat,
    CaptainsWheel,
    Calipers,
    IceCream,
    SneckoSkull,
    Ginger,
    Turnip,
    Tingsha,
    ToughBandages,
    GremlinHorn,
    TheSpecimen,
    LizardTail,
    Boot,
    Torii,
    TungstenRod,
    HandDrill,
    StrikeDummy,
    PaperKrane,
    CentennialPuzzle,
    MealTicket,
    MawBank,
    JuzuBracelet,
    TinyChest,
    EternalFeather,
    AncientTeaSet,
    RegalPillow,
    MeatOnTheBone,
    Omamori,
    DarkstonePeriapt,
    CeramicFish,
    FrozenEgg,
    MoltenEgg,
    ToxicEgg,
    ToyOrnithopter,
    SmilingMask,
    DeadBranch,
    DuVuDoll,
    Pantograph,
    SlingOfCourage,
    Strawberry,
    Pear,
    Mango,
    OldCoin,
    PotionBelt,
    WarPaint,
    Whetstone,
    EmptyCage,
    PandorasBox,
    PenNib,
    FossilizedHelix,
    PreservedInsect,
    UnceasingTop,
    BlueCandle,
    MedicalKit,
    SpiritPoop,
    WarpedTongs,
    CultistHeadpiece,
    FaceOfCleric,
    NlothsHungryFace,
    SsserpentHead,
    OddMushroom,
    PhilosopherStone,
    CoffeeDripper,
    FusionHammer,
    Sozu,
    CursedKey,
    BustedCrown,
    SlaversCollar,
    Ectoplasm,
    VelvetChoker,
    WristBlade,
    HoveringKite,
    DreamCatcher,
    Cauldron,
    MembershipCard,
    TheCourier,
    GamblingChip,
    BottledFlame,
    BottledLightning,
    BottledTornado,
    Matryoshka,
    Orrery,
    Toolbox,
    SneckoEye,
    Astrolabe,
    CallingBell,
    TinyHouse,
    BlackStar,
    Girya,
    PeacePipe,
    Shovel,
    WingBoots,
    QuestionCard,
    SingingBowl,
    PrayerWheel,
    RunicPyramid,
    RingOfTheSerpent,
    SacredBark,
}

impl From<RelicName> for PyRelicName {
    fn from(name: RelicName) -> Self {
        match name {
            RelicName::SnakeRing => Self::SnakeRing,
            RelicName::Akabeko => Self::Akabeko,
            RelicName::Anchor => Self::Anchor,
            RelicName::BagOfMarbles => Self::BagOfMarbles,
            RelicName::BagOfPreparation => Self::BagOfPreparation,
            RelicName::BloodVial => Self::BloodVial,
            RelicName::BronzeScales => Self::BronzeScales,
            RelicName::Kunai => Self::Kunai,
            RelicName::NinjaScroll => Self::NinjaScroll,
            RelicName::OddlySmoothStone => Self::OddlySmoothStone,
            RelicName::Shuriken => Self::Shuriken,
            RelicName::ThreadAndNeedle => Self::ThreadAndNeedle,
            RelicName::TwistedFunnel => Self::TwistedFunnel,
            RelicName::Vajra => Self::Vajra,
            RelicName::Circlet => Self::Circlet,
            RelicName::GoldenIdol => Self::GoldenIdol,
            RelicName::Lantern => Self::Lantern,
            RelicName::ClockworkSouvenir => Self::ClockworkSouvenir,
            RelicName::GremlinVisage => Self::GremlinVisage,
            RelicName::RedMask => Self::RedMask,
            RelicName::Nunchaku => Self::Nunchaku,
            RelicName::InkBottle => Self::InkBottle,
            RelicName::LetterOpener => Self::LetterOpener,
            RelicName::OrnamentalFan => Self::OrnamentalFan,
            RelicName::BirdFacedUrn => Self::BirdFacedUrn,
            RelicName::MummifiedHand => Self::MummifiedHand,
            RelicName::OrangePellets => Self::OrangePellets,
            RelicName::StrangeSpoon => Self::StrangeSpoon,
            RelicName::ChemicalX => Self::ChemicalX,
            RelicName::ArtOfWar => Self::ArtOfWar,
            RelicName::Orichalcum => Self::Orichalcum,
            RelicName::Pocketwatch => Self::Pocketwatch,
            RelicName::StoneCalendar => Self::StoneCalendar,
            RelicName::Abacus => Self::Abacus,
            RelicName::Sundial => Self::Sundial,
            RelicName::WhiteBeastStatue => Self::WhiteBeastStatue,
            RelicName::DollysMirror => Self::DollysMirror,
            RelicName::LeesWaffle => Self::LeesWaffle,
            RelicName::HappyFlower => Self::HappyFlower,
            RelicName::IncenseBurner => Self::IncenseBurner,
            RelicName::MercuryHourglass => Self::MercuryHourglass,
            RelicName::HornCleat => Self::HornCleat,
            RelicName::CaptainsWheel => Self::CaptainsWheel,
            RelicName::Calipers => Self::Calipers,
            RelicName::IceCream => Self::IceCream,
            RelicName::SneckoSkull => Self::SneckoSkull,
            RelicName::Ginger => Self::Ginger,
            RelicName::Turnip => Self::Turnip,
            RelicName::Tingsha => Self::Tingsha,
            RelicName::ToughBandages => Self::ToughBandages,
            RelicName::GremlinHorn => Self::GremlinHorn,
            RelicName::TheSpecimen => Self::TheSpecimen,
            RelicName::LizardTail => Self::LizardTail,
            RelicName::Boot => Self::Boot,
            RelicName::Torii => Self::Torii,
            RelicName::TungstenRod => Self::TungstenRod,
            RelicName::HandDrill => Self::HandDrill,
            RelicName::StrikeDummy => Self::StrikeDummy,
            RelicName::PaperKrane => Self::PaperKrane,
            RelicName::CentennialPuzzle => Self::CentennialPuzzle,
            RelicName::MealTicket => Self::MealTicket,
            RelicName::MawBank => Self::MawBank,
            RelicName::JuzuBracelet => Self::JuzuBracelet,
            RelicName::TinyChest => Self::TinyChest,
            RelicName::EternalFeather => Self::EternalFeather,
            RelicName::AncientTeaSet => Self::AncientTeaSet,
            RelicName::RegalPillow => Self::RegalPillow,
            RelicName::MeatOnTheBone => Self::MeatOnTheBone,
            RelicName::Omamori => Self::Omamori,
            RelicName::DarkstonePeriapt => Self::DarkstonePeriapt,
            RelicName::CeramicFish => Self::CeramicFish,
            RelicName::FrozenEgg => Self::FrozenEgg,
            RelicName::MoltenEgg => Self::MoltenEgg,
            RelicName::ToxicEgg => Self::ToxicEgg,
            RelicName::ToyOrnithopter => Self::ToyOrnithopter,
            RelicName::SmilingMask => Self::SmilingMask,
            RelicName::DeadBranch => Self::DeadBranch,
            RelicName::DuVuDoll => Self::DuVuDoll,
            RelicName::Pantograph => Self::Pantograph,
            RelicName::SlingOfCourage => Self::SlingOfCourage,
            RelicName::Strawberry => Self::Strawberry,
            RelicName::Pear => Self::Pear,
            RelicName::Mango => Self::Mango,
            RelicName::OldCoin => Self::OldCoin,
            RelicName::PotionBelt => Self::PotionBelt,
            RelicName::WarPaint => Self::WarPaint,
            RelicName::Whetstone => Self::Whetstone,
            RelicName::EmptyCage => Self::EmptyCage,
            RelicName::PandorasBox => Self::PandorasBox,
            RelicName::PenNib => Self::PenNib,
            RelicName::FossilizedHelix => Self::FossilizedHelix,
            RelicName::PreservedInsect => Self::PreservedInsect,
            RelicName::UnceasingTop => Self::UnceasingTop,
            RelicName::BlueCandle => Self::BlueCandle,
            RelicName::MedicalKit => Self::MedicalKit,
            RelicName::SpiritPoop => Self::SpiritPoop,
            RelicName::WarpedTongs => Self::WarpedTongs,
            RelicName::CultistHeadpiece => Self::CultistHeadpiece,
            RelicName::FaceOfCleric => Self::FaceOfCleric,
            RelicName::NlothsHungryFace => Self::NlothsHungryFace,
            RelicName::SsserpentHead => Self::SsserpentHead,
            RelicName::OddMushroom => Self::OddMushroom,
            RelicName::PhilosopherStone => Self::PhilosopherStone,
            RelicName::CoffeeDripper => Self::CoffeeDripper,
            RelicName::FusionHammer => Self::FusionHammer,
            RelicName::Sozu => Self::Sozu,
            RelicName::CursedKey => Self::CursedKey,
            RelicName::BustedCrown => Self::BustedCrown,
            RelicName::SlaversCollar => Self::SlaversCollar,
            RelicName::Ectoplasm => Self::Ectoplasm,
            RelicName::VelvetChoker => Self::VelvetChoker,
            RelicName::WristBlade => Self::WristBlade,
            RelicName::HoveringKite => Self::HoveringKite,
            RelicName::DreamCatcher => Self::DreamCatcher,
            RelicName::Cauldron => Self::Cauldron,
            RelicName::MembershipCard => Self::MembershipCard,
            RelicName::TheCourier => Self::TheCourier,
            RelicName::GamblingChip => Self::GamblingChip,
            RelicName::BottledFlame => Self::BottledFlame,
            RelicName::BottledLightning => Self::BottledLightning,
            RelicName::BottledTornado => Self::BottledTornado,
            RelicName::Matryoshka => Self::Matryoshka,
            RelicName::Orrery => Self::Orrery,
            RelicName::Toolbox => Self::Toolbox,
            RelicName::SneckoEye => Self::SneckoEye,
            RelicName::Astrolabe => Self::Astrolabe,
            RelicName::CallingBell => Self::CallingBell,
            RelicName::TinyHouse => Self::TinyHouse,
            RelicName::BlackStar => Self::BlackStar,
            RelicName::Girya => Self::Girya,
            RelicName::PeacePipe => Self::PeacePipe,
            RelicName::Shovel => Self::Shovel,
            RelicName::WingBoots => Self::WingBoots,
            RelicName::QuestionCard => Self::QuestionCard,
            RelicName::SingingBowl => Self::SingingBowl,
            RelicName::PrayerWheel => Self::PrayerWheel,
            RelicName::RunicPyramid => Self::RunicPyramid,
            RelicName::RingOfTheSerpent => Self::RingOfTheSerpent,
            RelicName::SacredBark => Self::SacredBark,
        }
    }
}

impl From<PyRelicName> for RelicName {
    fn from(name: PyRelicName) -> Self {
        match name {
            PyRelicName::SnakeRing => Self::SnakeRing,
            PyRelicName::Akabeko => Self::Akabeko,
            PyRelicName::Anchor => Self::Anchor,
            PyRelicName::BagOfMarbles => Self::BagOfMarbles,
            PyRelicName::BagOfPreparation => Self::BagOfPreparation,
            PyRelicName::BloodVial => Self::BloodVial,
            PyRelicName::BronzeScales => Self::BronzeScales,
            PyRelicName::Kunai => Self::Kunai,
            PyRelicName::NinjaScroll => Self::NinjaScroll,
            PyRelicName::OddlySmoothStone => Self::OddlySmoothStone,
            PyRelicName::Shuriken => Self::Shuriken,
            PyRelicName::ThreadAndNeedle => Self::ThreadAndNeedle,
            PyRelicName::TwistedFunnel => Self::TwistedFunnel,
            PyRelicName::Vajra => Self::Vajra,
            PyRelicName::Circlet => Self::Circlet,
            PyRelicName::GoldenIdol => Self::GoldenIdol,
            PyRelicName::Lantern => Self::Lantern,
            PyRelicName::ClockworkSouvenir => Self::ClockworkSouvenir,
            PyRelicName::GremlinVisage => Self::GremlinVisage,
            PyRelicName::RedMask => Self::RedMask,
            PyRelicName::Nunchaku => Self::Nunchaku,
            PyRelicName::InkBottle => Self::InkBottle,
            PyRelicName::LetterOpener => Self::LetterOpener,
            PyRelicName::OrnamentalFan => Self::OrnamentalFan,
            PyRelicName::BirdFacedUrn => Self::BirdFacedUrn,
            PyRelicName::MummifiedHand => Self::MummifiedHand,
            PyRelicName::OrangePellets => Self::OrangePellets,
            PyRelicName::StrangeSpoon => Self::StrangeSpoon,
            PyRelicName::ChemicalX => Self::ChemicalX,
            PyRelicName::ArtOfWar => Self::ArtOfWar,
            PyRelicName::Orichalcum => Self::Orichalcum,
            PyRelicName::Pocketwatch => Self::Pocketwatch,
            PyRelicName::StoneCalendar => Self::StoneCalendar,
            PyRelicName::Abacus => Self::Abacus,
            PyRelicName::Sundial => Self::Sundial,
            PyRelicName::WhiteBeastStatue => Self::WhiteBeastStatue,
            PyRelicName::DollysMirror => Self::DollysMirror,
            PyRelicName::LeesWaffle => Self::LeesWaffle,
            PyRelicName::HappyFlower => Self::HappyFlower,
            PyRelicName::IncenseBurner => Self::IncenseBurner,
            PyRelicName::MercuryHourglass => Self::MercuryHourglass,
            PyRelicName::HornCleat => Self::HornCleat,
            PyRelicName::CaptainsWheel => Self::CaptainsWheel,
            PyRelicName::Calipers => Self::Calipers,
            PyRelicName::IceCream => Self::IceCream,
            PyRelicName::SneckoSkull => Self::SneckoSkull,
            PyRelicName::Ginger => Self::Ginger,
            PyRelicName::Turnip => Self::Turnip,
            PyRelicName::Tingsha => Self::Tingsha,
            PyRelicName::ToughBandages => Self::ToughBandages,
            PyRelicName::GremlinHorn => Self::GremlinHorn,
            PyRelicName::TheSpecimen => Self::TheSpecimen,
            PyRelicName::LizardTail => Self::LizardTail,
            PyRelicName::Boot => Self::Boot,
            PyRelicName::Torii => Self::Torii,
            PyRelicName::TungstenRod => Self::TungstenRod,
            PyRelicName::HandDrill => Self::HandDrill,
            PyRelicName::StrikeDummy => Self::StrikeDummy,
            PyRelicName::PaperKrane => Self::PaperKrane,
            PyRelicName::CentennialPuzzle => Self::CentennialPuzzle,
            PyRelicName::MealTicket => Self::MealTicket,
            PyRelicName::MawBank => Self::MawBank,
            PyRelicName::JuzuBracelet => Self::JuzuBracelet,
            PyRelicName::TinyChest => Self::TinyChest,
            PyRelicName::EternalFeather => Self::EternalFeather,
            PyRelicName::AncientTeaSet => Self::AncientTeaSet,
            PyRelicName::RegalPillow => Self::RegalPillow,
            PyRelicName::MeatOnTheBone => Self::MeatOnTheBone,
            PyRelicName::Omamori => Self::Omamori,
            PyRelicName::DarkstonePeriapt => Self::DarkstonePeriapt,
            PyRelicName::CeramicFish => Self::CeramicFish,
            PyRelicName::FrozenEgg => Self::FrozenEgg,
            PyRelicName::MoltenEgg => Self::MoltenEgg,
            PyRelicName::ToxicEgg => Self::ToxicEgg,
            PyRelicName::ToyOrnithopter => Self::ToyOrnithopter,
            PyRelicName::SmilingMask => Self::SmilingMask,
            PyRelicName::DeadBranch => Self::DeadBranch,
            PyRelicName::DuVuDoll => Self::DuVuDoll,
            PyRelicName::Pantograph => Self::Pantograph,
            PyRelicName::SlingOfCourage => Self::SlingOfCourage,
            PyRelicName::Strawberry => Self::Strawberry,
            PyRelicName::Pear => Self::Pear,
            PyRelicName::Mango => Self::Mango,
            PyRelicName::OldCoin => Self::OldCoin,
            PyRelicName::PotionBelt => Self::PotionBelt,
            PyRelicName::WarPaint => Self::WarPaint,
            PyRelicName::Whetstone => Self::Whetstone,
            PyRelicName::EmptyCage => Self::EmptyCage,
            PyRelicName::PandorasBox => Self::PandorasBox,
            PyRelicName::PenNib => Self::PenNib,
            PyRelicName::FossilizedHelix => Self::FossilizedHelix,
            PyRelicName::PreservedInsect => Self::PreservedInsect,
            PyRelicName::UnceasingTop => Self::UnceasingTop,
            PyRelicName::BlueCandle => Self::BlueCandle,
            PyRelicName::MedicalKit => Self::MedicalKit,
            PyRelicName::SpiritPoop => Self::SpiritPoop,
            PyRelicName::WarpedTongs => Self::WarpedTongs,
            PyRelicName::CultistHeadpiece => Self::CultistHeadpiece,
            PyRelicName::FaceOfCleric => Self::FaceOfCleric,
            PyRelicName::NlothsHungryFace => Self::NlothsHungryFace,
            PyRelicName::SsserpentHead => Self::SsserpentHead,
            PyRelicName::OddMushroom => Self::OddMushroom,
            PyRelicName::PhilosopherStone => Self::PhilosopherStone,
            PyRelicName::CoffeeDripper => Self::CoffeeDripper,
            PyRelicName::FusionHammer => Self::FusionHammer,
            PyRelicName::Sozu => Self::Sozu,
            PyRelicName::CursedKey => Self::CursedKey,
            PyRelicName::BustedCrown => Self::BustedCrown,
            PyRelicName::SlaversCollar => Self::SlaversCollar,
            PyRelicName::Ectoplasm => Self::Ectoplasm,
            PyRelicName::VelvetChoker => Self::VelvetChoker,
            PyRelicName::WristBlade => Self::WristBlade,
            PyRelicName::HoveringKite => Self::HoveringKite,
            PyRelicName::DreamCatcher => Self::DreamCatcher,
            PyRelicName::Cauldron => Self::Cauldron,
            PyRelicName::MembershipCard => Self::MembershipCard,
            PyRelicName::TheCourier => Self::TheCourier,
            PyRelicName::GamblingChip => Self::GamblingChip,
            PyRelicName::BottledFlame => Self::BottledFlame,
            PyRelicName::BottledLightning => Self::BottledLightning,
            PyRelicName::BottledTornado => Self::BottledTornado,
            PyRelicName::Matryoshka => Self::Matryoshka,
            PyRelicName::Orrery => Self::Orrery,
            PyRelicName::Toolbox => Self::Toolbox,
            PyRelicName::SneckoEye => Self::SneckoEye,
            PyRelicName::Astrolabe => Self::Astrolabe,
            PyRelicName::CallingBell => Self::CallingBell,
            PyRelicName::TinyHouse => Self::TinyHouse,
            PyRelicName::BlackStar => Self::BlackStar,
            PyRelicName::Girya => Self::Girya,
            PyRelicName::PeacePipe => Self::PeacePipe,
            PyRelicName::Shovel => Self::Shovel,
            PyRelicName::WingBoots => Self::WingBoots,
            PyRelicName::QuestionCard => Self::QuestionCard,
            PyRelicName::SingingBowl => Self::SingingBowl,
            PyRelicName::PrayerWheel => Self::PrayerWheel,
            PyRelicName::RunicPyramid => Self::RunicPyramid,
            PyRelicName::RingOfTheSerpent => Self::RingOfTheSerpent,
            PyRelicName::SacredBark => Self::SacredBark,
        }
    }
}

#[pyclass(
    skip_from_py_object,
    eq,
    eq_int,
    frozen,
    name = "RelicTier",
    module = "slai.slai"
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PyRelicTier {
    Starter,
    Common,
    Uncommon,
    Rare,
    Boss,
    Shop,
    Special,
}

impl From<RelicTier> for PyRelicTier {
    fn from(tier: RelicTier) -> Self {
        match tier {
            RelicTier::Starter => Self::Starter,
            RelicTier::Common => Self::Common,
            RelicTier::Uncommon => Self::Uncommon,
            RelicTier::Rare => Self::Rare,
            RelicTier::Boss => Self::Boss,
            RelicTier::Shop => Self::Shop,
            RelicTier::Special => Self::Special,
        }
    }
}

#[pyclass(
    skip_from_py_object,
    frozen,
    get_all,
    name = "Relic",
    module = "slai.slai"
)]
#[derive(Debug, Clone)]
pub struct PyRelic {
    pub name: PyRelicName,
    pub tier: PyRelicTier,
    pub counter: i16,
    pub used_up: bool,
    pub effects_on_combat_start: Vec<PyEffect>,
}

pub(crate) fn snapshot_relic(entity: &Entity) -> PyRelic {
    PyRelic {
        name: entity.relic_name.into(),
        tier: entity.relic_tier.into(),
        counter: entity.relic_counter,
        used_up: entity.relic_used_up,
        effects_on_combat_start: entity
            .relic_effects_on_combat_start
            .iter()
            .map(snapshot_effect)
            .collect(),
    }
}
